### ISSUE TITLE
Why do you add sleep in streaming client?

### ISSUE THREAD

**Issue by JaheimLee** [k2-fsa/sherpa#105]
https://github.com/k2-fsa/sherpa/blob/d958043f1680bdef666a97699d2aaa9fcd4c91fa/sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_client.py#L103
It costs 0.25s(4096/16000) each chunk and make it so slow. I didn't find any difference with/without sleep. Is it because if many clients request the server, there may be some unknown errors?

**Comment by csukuangfj** [comment]
It is to simulate the real condition. In reality, you need some time to capture some audio samples.
For instance, if the sampling rate is 16kHz, you need 1 second to capture 16000 audio samples.

**Comment by JaheimLee** [comment]
Oh, thanks!
