### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by shaynemei** [k2-fsa/sherpa#109]
Sherpa server shuts down on segmentation fault. Do you have any recommendation on how to investigate the cause of this?

![snap 2022-09-06 at 4 16 29 PM](https://user-images.githubusercontent.com/31003116/188988597-c5a2f2ed-af4f-46ba-95e9-e2f9732bebdc.png)

**Comment by csukuangfj** [comment]
Is it reproducible?

gdb --args python3 xxx.py [your script args]

may give you more info about the error.

**Comment by shaynemei** [comment]
Thanks I'm still trying to reproduce it.

**Comment by shaynemei** [comment]
this seems to be related to not enough memory on the host machine. Closing now.

**Comment by danpovey** [comment]
.. OK but that shouldn't really die with segfault if it's OOM.

**Comment by shaynemei** [comment]
we will report back again with the exact logs if we were able to reproduce it.
