### ISSUE TITLE
Install fails with new version of kaldi_native_io

### ISSUE THREAD

**Issue by MolochKel** [k2-fsa/sherpa#110]
Running: `pip install --verbose k2-sherpa` worked fine yesterday. Today it fails.

Seems to be caused by kaldi_native_io:1.14

Edited requirements.txt with `kaldi_native_io==1.12` and installation works again.

**Comment by csukuangfj** [comment]
Could you show the logs?

**Comment by MolochKel** [comment]
From before downgrading to kaldi_native_io:1.12
[output.txt](https://github.com/k2-fsa/sherpa/files/9576887/output.txt)

**Comment by csukuangfj** [comment]
I see the problem.

It should be fixed by https://github.com/k2-fsa/sherpa/pull/111

Could you try sherpa v0.8?
(I have uploaded v0.8 to PyPI )

**Comment by MolochKel** [comment]
Yup, that seems to have done it. Managed to install v0.8 with kaldi_native_io:1.14.
Thank you!
