### ISSUE TITLE
I build sherpa failed with error cc1plus: all warnings being treated as errors ?

### ISSUE THREAD

**Issue by trangtv57** [k2-fsa/sherpa#126]
Hi, I have build sherpa and get message error:
![image](https://user-images.githubusercontent.com/12123427/191061105-6f808a58-c819-479d-839b-300743b249f5.png)
how can i figure out this problem, I know I can pass parameter but don't know where

**Comment by csukuangfj** [comment]
Which version of sherpa are you using?
How do you install it?

**Comment by trangtv57** [comment]
I have pass this error and get another error:
![image](https://user-images.githubusercontent.com/12123427/191189771-1c9fb4d9-61b7-4d75-9d4e-a5754b934215.png)
threads found true. But it's got error:
![image](https://user-images.githubusercontent.com/12123427/191189902-9cf99e7c-205f-429b-90e2-33fc391bd710.png)
and pthreads not found .
I build with cuda 11.3, torch 1.11.0+cu113

**Comment by csukuangfj** [comment]
> I have pass this error and get another error:

Does it prevent CMake from running?

**Comment by trangtv57** [comment]
I'm not sure I understand your question? I just build simple file c and compile with -pthread :
like this: gcc -o abc abc.cpp -pthread, it's compile program ok.
I try to add pthread by string(APPEND CMAKE_CXX_FLAGS " -pthread ")  but it's still get this error

**Comment by csukuangfj** [comment]
> I'm not sure I understand your question?

Did CMake fail?

Could you post all of the logs? It is hard to figure out what the issue is from a limited context.

**Comment by trangtv57** [comment]
[CMakeError.log](https://github.com/k2-fsa/sherpa/files/9605163/CMakeError.log)
[CMakeOutput.log](https://github.com/k2-fsa/sherpa/files/9605164/CMakeOutput.log)
[log_install_sherpa.txt](https://github.com/k2-fsa/sherpa/files/9605165/log_install_sherpa.txt)
log install sherpa is file log after I run python setup.py install. Tks @csukuangfj

**Comment by csukuangfj** [comment]
Could you update your CMake?

```
pip install cmake
```
should work.

**Comment by trangtv57** [comment]
what's the fix? haha, tks you so much, It's work.
