### ISSUE TITLE
undefined referece to kaldi_io

### ISSUE THREAD

**Issue by trangtv57** [k2-fsa/sherpa#129]
I have install sherpa done in server, but failed in my computer. Sherpa build lib failed because don't see kaldi_io libriary, But I check it's exist. It's my log. Can you help me to check it? tks.
[log_error.txt](https://github.com/k2-fsa/sherpa/files/9613797/log_error.txt)

**Comment by csukuangfj** [comment]
Could you try the latest sherpa?

**Comment by trangtv57** [comment]
install lastest version fixed it. Tks
