### ISSUE TITLE
Can we kill the server via rogue clients

### ISSUE THREAD

**Issue by ngoel17** [k2-fsa/sherpa#14]
First of all, it's a great start. This issue is more of an improvement suggestion
   If the number of clients increases, the memory consumption and CPU consumption both will increase. At some point, it's better to refuse an additional connection than to risk the segfault or a sluggish server. The max-clients parameter is needed.

**Comment by csukuangfj** [comment]
Thanks for the suggestions.

`sherpa` is using `websockets` for communication. I have checked its documentation and find that there is no `max-clients` parameter in it.  It does not support limiting the number of connections, I think.

https://github.com/aaugustin/websockets/issues/772#issuecomment-640012907
says `websockets` can handle 10k to 20k connections easily.

The [documentation](https://websockets.readthedocs.io/en/9.0.1/api/server.html#starting-a-server) indeed describes two parameters that are useful to limit the memory 
consumption of each connection:

- max_queue, limiting the number of messages in the input queue per connection. The default value is 128
- max_size,  limiting the message size in bytes per connection. The default value is 1 MB

If the input queue of a connection is close to full, I think the TCP congestion control algorithm will slow down the
sending speed of the client to avoid packet loss. 

Can I provide the above two parameters to limit the memory consumption per connection? You can tune them for your needs.

**Comment by ngoel17** [comment]
I don't think exposing those will do much.  Maybe [process_request()](https://websockets.readthedocs.io/en/9.0.1/api/server.html#websockets.legacy.server.WebSocketServerProtocol.process_request) is a better location to handle this. It can look at the current limit and refuse a new connection if above the limit (maybe with a code and message).

**Comment by csukuangfj** [comment]
@ngoel17 
I think #15 addresses your concern.
