### ISSUE TITLE
Modified beam search for streaming transducer

### ISSUE THREAD

**Issue by ezerhouni** [k2-fsa/sherpa#141]
It seems that ```streaming_modified_beam_search``` is missing for streaming_pruned_transducer. Is there a reason for it ? If not I can take of it 

cc @csukuangfj

**Comment by csukuangfj** [comment]
Thanks!

The only reason is that when we added `streaming_pruned_transducer`, we did not port streaming_modified_beam_search to it.

**Comment by ezerhouni** [comment]
Closing
