### ISSUE TITLE
[Help wanted] Add support for LSTM-transducer to C++ streaming ASR API

### ISSUE THREAD

**Issue by csukuangfj** [k2-fsa/sherpa#149]
The current C++ API supports only conv-emformer models, we need to support LSTM-transducer models.

Supporting LSTM-transducer can be implemented in the following steps:
1.  Merge #147 
2. Finish #148 
3. Add `StackStates` and `UnStackStates` for 
https://github.com/k2-fsa/sherpa/blob/b1634288e34f97bc5985eca87126d07f3294bda8/sherpa/csrc/rnnt_lstm_model.h#L35

(Step 3 may be the most difficult part. Please also add c++ test for it during the implementation)

4. Change
https://github.com/k2-fsa/sherpa/blob/b1634288e34f97bc5985eca87126d07f3294bda8/sherpa/csrc/online_asr.h#L113
to
```
 std::unique_ptr<RnntModel> model_; 
```
Also, we should write some code to decide whether to construct an instance of `RnntLstmModel` or `RnntConvEmformerModel`

5. Update the documentation
https://github.com/k2-fsa/sherpa/tree/master/docs/source/cpp/online_asr

Step 2, 3, 4, and 5 can be implemented in separate PRs.

---

We can add streaming conformer model to C++ streaming ASR API in a separate PR.

**Comment by csukuangfj** [comment]
Please leave a message in case you want to pick it up so that others can implement other TODOs.

**Comment by beyond-boy** [comment]
how to implement  Conformer transducer based streaming ASR in c++?  @csukuangfj

**Comment by csukuangfj** [comment]
> how to implement Conformer transducer based streaming ASR in c++? @csukuangfj

It is listed in the TODOs of this PR and in https://github.com/k2-fsa/sherpa/issues/148

Do you want to have a try?

**Comment by csukuangfj** [comment]
> how to implement Conformer transducer based streaming ASR in c++? @csukuangfj

@beyond-boy 
#171 implements LSTM-transducer-based streaming ASR in C++. It can be used as a reference
to implement conformer-transducer-based streaming ASR in C++ if you would like to have a try.
