### ISSUE TITLE
No rule to make libk2_torch_api.so', needed by 'lib/libsherpa_core.so'.  Stop.

### ISSUE THREAD

**Issue by teowenshen** [k2-fsa/sherpa#156]
Hi, I faced this error when installing sherpa. 

I am not sure if this would help - I should clarify that, previously, I managed to successfully install sherpa on another machine (in a docker) using this same directory (on an external data server). So, this is the second time I am using the same directory to install sherpa, on another machine. 

I couldn't understand what went wrong based on the error message itself. I confirmed that k2 is working in this container using the [test script](https://k2-fsa.github.io/k2/installation/from_source.html), and I have used this exact container to train other models before. 

> [ 59%] Building CXX object sherpa/csrc/CMakeFiles/sherpa_core.dir/rnnt_emformer_model.cc.o
> In file included from /opt/conda/lib/python3.7/site-packages/torch/include/c10/core/DeviceType.h:8:0,
>                  from /opt/conda/lib/python3.7/site-packages/torch/include/c10/core/Device.h:3,
>                  from /opt/conda/lib/python3.7/site-packages/torch/include/c10/core/Allocator.h:6,
>                  from /opt/conda/lib/python3.7/site-packages/torch/include/ATen/ATen.h:7,
>                  from /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
>                  from /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
>                  from /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
>                  from /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
>                  from /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
>                  from /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
>                  from /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
>                  from /mnt/minami_data_server/t2131178/sherpa/sherpa/csrc/hypothesis.h:27,
>                  from /mnt/minami_data_server/t2131178/sherpa/sherpa/csrc/rnnt_beam_search.h:23,
>                  from /mnt/minami_data_server/t2131178/sherpa/sherpa/csrc/rnnt_beam_search.cc:19:
> /mnt/minami_data_server/t2131178/sherpa/sherpa/csrc/rnnt_beam_search.cc: In function â€˜at::Tensor sherpa::StreamingGreedySearch(sherpa::RnntModel&, at::Tensor, at::Tensor, const std::vector<int, std::allocator<int> >&, std::vector<std::vector<int, std::allocator<int> > >*, std::vector<int, std::allocator<int> >*, std::vector<std::vector<int, std::allocator<int> > >*)â€™:
> /mnt/minami_data_server/t2131178/sherpa/sherpa/csrc/rnnt_beam_search.cc:218:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>    TORCH_CHECK(encoder_out.size(0) == hyps->size(), encoder_out.size(0), " vs ",
>                ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
> /mnt/minami_data_server/t2131178/sherpa/sherpa/csrc/rnnt_beam_search.cc: In function â€˜std::vector<std::vector<int, std::allocator<int> > > sherpa::ModifiedBeamSearch(sherpa::RnntModel&, at::Tensor, at::Tensor, int32_t)â€™:
> /mnt/minami_data_server/t2131178/sherpa/sherpa/csrc/rnnt_beam_search.cc:323:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>      if (cur_batch_size < cur.size()) {
>          ~~~~~~~~~~~~~~~^~~~~~~~~~~~
> /mnt/minami_data_server/t2131178/sherpa/sherpa/csrc/rnnt_beam_search.cc:349:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>      for (int32_t k = 0; k != prev.size(); ++k) {
>                          ~~^~~~~~~~~~~~~~
> [ 60%] Building CXX object sherpa/csrc/CMakeFiles/sherpa_core.dir/rnnt_lstm_model.cc.o
> make[2]: *** No rule to make target '/opt/conda/lib/python3.7/site-packages/k2-1.19.dev20220919+cuda11.3.torch1.12.1-py3.7-linux-x86_64.egg/k2/lib/libk2_torch_api.so', needed by 'lib/libsherpa_core.so'.  Stop.
> make[2]: *** Waiting for unfinished jobs....
> [ 62%] Building CXX object sherpa/csrc/CMakeFiles/sherpa_core.dir/symbol_table.cc.o
> CMakeFiles/Makefile2:356: recipe for target 'sherpa/csrc/CMakeFiles/sherpa_core.dir/all' failed
> make[1]: *** [sherpa/csrc/CMakeFiles/sherpa_core.dir/all] Error 2
> Makefile:135: recipe for target 'all' failed
> make: *** [all] Error 2
> Traceback (most recent call last):
>   File "setup.py", line 117, in <module>
>     license="Apache licensed, as found in the LICENSE file",
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
>     return distutils.core.setup(**attrs)
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
>     return run_commands(dist)
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
>     dist.run_commands()
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
>     self.run_command(cmd)
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
>     super().run_command(command)
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
>     cmd_obj.run()
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/command/install.py", line 74, in run
>     self.do_egg_install()
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/command/install.py", line 123, in do_egg_install
>     self.run_command('bdist_egg')
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
>     super().run_command(command)
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
>     cmd_obj.run()
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 165, in run
>     cmd = self.call_command('install_lib', warn_dir=0)
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
>     self.run_command(cmdname)
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
>     super().run_command(command)
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
>     cmd_obj.run()
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
>     self.build()
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/_distutils/command/install_lib.py", line 107, in build
>     self.run_command('build_ext')
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
>     super().run_command(command)
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
>     cmd_obj.run()
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
>     _build_ext.run(self)
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
>     self.build_extensions()
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
>     self._build_extensions_serial()
>   File "/opt/conda/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
>     self.build_extension(ext)
>   File "/mnt/minami_data_server/t2131178/sherpa/cmake/cmake_extension.py", line 117, in build_extension
>     "\nBuild sherpa failed. Please check the error message.\n"
> Exception: 
> Build sherpa failed. Please check the error message.
> You can ask for help by creating an issue on GitHub.
> 
> Click:
> 	https://github.com/k2-fsa/sherpa/issues/new

**Comment by csukuangfj** [comment]
Could you tell us which version of k2 you are using?
```
python3 -m k2.version
```
should give you such information.

**Comment by teowenshen** [comment]
Please find my k2 version as below. 

> Collecting environment information...
> 
> k2 version: 1.20
> Build type: Release
> Git SHA1: c6d5fd51f51b76178f1f56f409f4212d78aae4e5
> Git date: Sat Sep 24 02:00:23 2022
> Cuda used to build k2: 11.3
> cuDNN used to build k2: 8.2.0
> Python version used to build k2: 3.7
> OS used to build k2: 
> CMake version: 3.18.0
> GCC version: 7.5.0
> CMAKE_CUDA_FLAGS:  -Wno-deprecated-gpu-targets   -lineinfo --expt-extended-lambda -use_fast_math -Xptxas=-w  --expt-extended-lambda -gencode arch=compute_35,code=sm_35  -lineinfo --expt-extended-lambda -use_fast_math -Xptxas=-w  --expt-extended-lambda -gencode arch=compute_50,code=sm_50  -lineinfo --expt-extended-lambda -use_fast_math -Xptxas=-w  --expt-extended-lambda -gencode arch=compute_60,code=sm_60  -lineinfo --expt-extended-lambda -use_fast_math -Xptxas=-w  --expt-extended-lambda -gencode arch=compute_61,code=sm_61  -lineinfo --expt-extended-lambda -use_fast_math -Xptxas=-w  --expt-extended-lambda -gencode arch=compute_70,code=sm_70  -lineinfo --expt-extended-lambda -use_fast_math -Xptxas=-w  --expt-extended-lambda -gencode arch=compute_75,code=sm_75  -lineinfo --expt-extended-lambda -use_fast_math -Xptxas=-w  --expt-extended-lambda -gencode arch=compute_80,code=sm_80  -lineinfo --expt-extended-lambda -use_fast_math -Xptxas=-w  --expt-extended-lambda -gencode arch=compute_86,code=sm_86 -DONNX_NAMESPACE=onnx_c2 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_86,code=compute_86 -Xcudafe --diag_suppress=cc_clobber_ignored,--diag_suppress=integer_sign_change,--diag_suppress=useless_using_declaration,--diag_suppress=set_but_not_used,--diag_suppress=field_without_dll_interface,--diag_suppress=base_class_has_different_dll_interface,--diag_suppress=dll_interface_conflict_none_assumed,--diag_suppress=dll_interface_conflict_dllexport_assumed,--diag_suppress=implicit_return_from_non_void_function,--diag_suppress=unsigned_compare_with_zero,--diag_suppress=declared_but_not_referenced,--diag_suppress=bad_friend_decl --expt-relaxed-constexpr --expt-extended-lambda -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options -Wall  --compiler-options -Wno-strict-overflow  --compiler-options -Wno-unknown-pragmas 
> CMAKE_CXX_FLAGS:  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-unused-variable  -Wno-strict-overflow 
> PyTorch version used to build k2: 1.12.1
> PyTorch is using Cuda: 11.3
> NVTX enabled: True
> With CUDA: True
> Disable debug: True
> Sync kernels : False
> Disable checks: False
> Max cpu memory allocate: 214748364800 bytes (or 200.0 GB)
> k2 abort: False
> __file__: /opt/conda/lib/python3.7/site-packages/k2-1.20.dev20221001+cuda11.3.torch1.12.1-py3.7-linux-x86_64.egg/k2/version/version.py
> _k2.__file__: /opt/conda/lib/python3.7/site-packages/k2-1.20.dev20221001+cuda11.3.torch1.12.1-py3.7-linux-x86_64.egg/_k2.cpython-37m-x86_64-linux-gnu.so

**Comment by csukuangfj** [comment]
But your logs says
> make[2]: *** No rule to make target '/opt/conda/lib/python3.7/site-packages/k2-1.19.dev20220919+cuda11.3.torch1.12.1-py3.7-linux-x86_64.egg/k2/lib/libk2_torch_api.so', needed by 'lib/libsherpa_core.so'. Stop.

So have you installed at least two versions of k2?
- /opt/conda/lib/python3.7/site-packages/k2-1.20.dev20221001+cuda11.3.torch1.12.1-py3.7-linux-x86_64.egg
- /opt/conda/lib/python3.7/site-packages/k2-1.19.dev20220919+cuda11.3.torch1.12.1-py3.7-linux-x86_64.egg

**Comment by csukuangfj** [comment]
Please install only a single version of k2 inside your environment.

If you want to install multiple versions, please create multiple **virtual environment**s for it.

**Comment by teowenshen** [comment]
> But your logs says
> 
> > make[2]: *** No rule to make target '/opt/conda/lib/python3.7/site-packages/k2-1.19.dev20220919+cuda11.3.torch1.12.1-py3.7-linux-x86_64.egg/k2/lib/libk2_torch_api.so', needed by 'lib/libsherpa_core.so'. Stop.
> 
> So have you installed at least two versions of k2?
> 
>     * /opt/conda/lib/python3.7/site-packages/k2-1.20.dev20221001+cuda11.3.torch1.12.1-py3.7-linux-x86_64.egg
> 
>     * /opt/conda/lib/python3.7/site-packages/k2-1.19.dev20220919+cuda11.3.torch1.12.1-py3.7-linux-x86_64.egg

Hmm. It would seem to be the case. All my `pip list` and `conda list` show 1.20. I must have made a mistake somewhere. 

Thanks for guiding me through the troubleshooting. Please allow me to leave this ticket open while I rebuild my docker image.

**Comment by csukuangfj** [comment]
By the way, I suggest that you use a virtual environment to manage your installed packages.

Also, if you use `pip instal xxx` to install  package `xxx`, you can use `pip uninstall xxx` to remove it.

If you use `conda install xxx` to install a package, you can use `conda remove xxx` to remove it.

**Comment by teowenshen** [comment]
Yes, managing these installed packages via virtual environments would be ideal. 

However, despite my best efforts, I couldn't seem to activate virtual conda environments across `RUN` commands in the Dockerfile to install the dependencies into said virtual environment. In the end, I had to settle for `base`, since dockers are - in a way - a type of environment management too. (If anyone manages to make conda environments work in Dockerfiles, please let me know!)

I guess it's a me problem now.

**Comment by csukuangfj** [comment]
Sorry, I don't have exerience about using a conda virtual environment within a docker.

But after googling about it, I can find lots of blogs about it.
For instance, one is
https://pythonspeed.com/articles/activate-conda-dockerfile/

**Comment by teowenshen** [comment]
I came across that blog too - I pretty much exhausted the entire Internet at that time. 

If I remember correctly, it was because one of the NGK packages (or their dependencies?) did not work with conda's environment.yml out of the box.

Anyway I will have some time on my hands once my model starts training. If I come up with any solution I will send in a pull request to Icefall.

**Comment by csukuangfj** [comment]
> I came across that blog too - I pretty much exhausted the entire Internet at that time.
> 
> If I remember correctly, it was because one of the NGK packages (or their dependencies?) did not work with conda's environment.yml out of the box.
> 
> Anyway I will have some time on my hands once my model starts training. If I come up with any solution I will send in a pull request to Icefall.

Thanks!

**Comment by teowenshen** [comment]
I found out what went wrong with the installation. 

I was using the exact same sherpa directory for the installation of another machine, and didn't notice that the first installation for the earlier machine had already created the build/, dist/ and k2_sherpa.egg-info directories. The other machine was using a newer k2, but somehow seeing that those directories had been created, the installation skipped a few steps and assumed the older k2. I think this is what created the version clash that you noticed. 

I'm still very new to C++. After a successful, working installation, do you know if the library .so files are copied into the python/site-packages environment, or do they still point here? I was thinking to delete the build/, dist/ and k2_sherpa.egg-info directories if they are no longer used after installation.

**Comment by csukuangfj** [comment]
If you use `python3 setup.py install`, you can safely remove the `./build` directory  after  the installation.

**Comment by teowenshen** [comment]
Great! Thank you so much.
