### ISSUE TITLE
Any result of LSTM transducer?

### ISSUE THREAD

**Issue by JaheimLee** [k2-fsa/sherpa#161]
Hi, is there any results of your LSTM transducer model? Including the speed, dev/test WER...

**Comment by csukuangfj** [comment]
Yes, please see
- https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/RESULTS.md#librispeech-bpe-training-results-pruned-stateless-lstm-rnn-t--gradient-filter

- https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/RESULTS.md#lstm_transducer_stateless2

<img width="775" alt="Screen Shot 2022-10-18 at 7 01 09 PM" src="https://user-images.githubusercontent.com/5284924/196412299-53bdad9f-6ca1-48c5-8e75-fae054e5ee69.png">
