### ISSUE TITLE
what's the best streaming mode for big dataset(egg,wenetspeech,gigaspeech) in k2?  

### ISSUE THREAD

**Issue by beyond-boy** [k2-fsa/sherpa#162]
In most cases, big dataset result is closer to industrial use scenarios

**Comment by csukuangfj** [comment]
For Chinese, I suggest using the model trained with the wenetspeech dataset.

For English, use the one with GigaSpeech.

**Comment by beyond-boy** [comment]
> 
thanks for reply
I don't need to use the model trained by those open dataset, I have much more labled industrial data(10w+ hour)，I just wan to know chose which streaming model to train will get best result(egg, for Chinese)，I don't have enough gpu resource to train all the streaming models

**Comment by csukuangfj** [comment]
> > 
> 
> thanks for reply I don't need to use the model trained by those open dataset, I have much more labled industrial data(10w+ hour)，I just wan to know chose which streaming model to train will get best result(egg, for Chinese)，I don't have enough gpu resource to train all the streaming models

I heard from someone that [ConvEmformer](https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/ASR/conv_emformer_transducer_stateless2) +RNN-T performs better than chunk-based
streaming conformer (CTC+attention decoder) when there is a large amount of training data, e.g., 10k+ hours.
(It is for Chinese). 

So personally I suggest that you can start with  [ConvEmformer](https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/ASR/conv_emformer_transducer_stateless2)

**Comment by beyond-boy** [comment]
> > > 
> > 
> > 
> > thanks for reply I don't need to use the model trained by those open dataset, I have much more labled industrial data(10w+ hour)，I just wan to know chose which streaming model to train will get best result(egg, for Chinese)，I don't have enough gpu resource to train all the streaming models
> 
> I heard from someone that [ConvEmformer](https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/ASR/conv_emformer_transducer_stateless2) +RNN-T performs better than chunk-based streaming conformer (CTC+attention decoder) when there is a large amount of training data, e.g., 10k+ hours. (It is for Chinese).
> 
> So personally I suggest that you can start with [ConvEmformer](https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/ASR/conv_emformer_transducer_stateless2)

thanks
