### ISSUE TITLE
C++ websockets missing fields at RnntConvEmformerModel

### ISSUE THREAD

**Issue by kolyaflash** [k2-fsa/sherpa#173]
Hi @csukuangfj,

I just tried to run C++ websockets streaming server. Awesome new feature, thank you!

Unfortunately, it fails with `ObjectAttributeError` for model `icefall_librispeech_streaming_pruned_transducer_stateless2`. Similar problem with `icefall-asr-librispeech-pruned-stateless-emformer-rnnt2`.

This field is added in `PybindRnntEmformerModel`, which is not the case for c++ api. 

Is it something that needs to be fixed in server code or it needs model to be created with c++ instead of python?

```
/usr/src/sherpa/build/bin/online_websocket_server --use-gpu=false --port=6006 --num-work-threads=5 --nn-model=/k2-models/online/cpu_jit-epoch-24-avg-10.pt --tokens=/k2-models/online/lang_bpe_500/tokens.txt --decoding-method=greedy_search --log-file=./log.txt --decoding-method=modified_beam_search 

terminate called after throwing an instance of 'torch::jit::ObjectAttributeError'
  what():  __torch__.conformer.Conformer (of Python compilation unit at: 0x55907bb1f080) does not have a field with name 'chunk_length'
Aborted (core dumped)
```

```
/usr/src/sherpa/build/bin/online_websocket_server --use-gpu=false --port=6006 --num-work-threads=5 --nn-model=/k2-models/online/cpu_jit-epoch-39-avg-6-use-averaged-model-1.pt --tokens=/k2-models/online/tokens.txt --decoding-method=greedy_search --log-file=./log.txt 

terminate called after throwing an instance of 'torch::jit::ObjectAttributeError'
  what():  __torch__.joiner.Joiner (of Python compilation unit at: 0x56533ecc3080) does not have a field with name 'encoder_proj'
Aborted (core dumped)
```

**Comment by csukuangfj** [comment]
@kolyaflash 
Only the streaming [conv-emformer](https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/ASR/conv_emformer_transducer_stateless2) model is supported at present. I am supporting [streaming conformer](https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/ASR/pruned_transducer_stateless2) and [emformer](https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/ASR/pruned_stateless_emformer_rnnt2).

Please refer to
https://github.com/k2-fsa/sherpa/pull/172#issuecomment-1294724295
for usage.

**Comment by kolyaflash** [comment]
Great, thank you @csukuangfj!
