### ISSUE TITLE
Do we need endpointing?

### ISSUE THREAD

**Issue by ngoel17** [k2-fsa/sherpa#19]
Wenet followed the approach of endpointing. https://github.com/wenet-e2e/wenet/blob/main/runtime/core/decoder/ctc_endpoint.h
I think the decode can handle reasonably long conversations but a phone conversation could easily go above 10 minutes, and if we are working with classroom lectures etc, it could be more than an hour. One could even come up with some always-on applications. The question is not just about the accuracy, but also the memory requirements to store the output (instead of dumping it and moving on after every endpoint). Do we need endpointing?

**Comment by ngoel17** [comment]
It appears that the server gets stuck on long files such as 10 minutes of Audio.

**Comment by csukuangfj** [comment]
> It appears that the server gets stuck on long files such as 10 minutes of Audio.

Are you using the offline server or the streaming server?
Are you using the latest sherpa that fixes the issues in https://github.com/k2-fsa/sherpa/issues/20 ?

**Comment by ngoel17** [comment]
The issue is with the streaming server, and with the latest #22 version. Audio should be long (10 min or more) to replicate the issue.

**Comment by csukuangfj** [comment]
I think the streaming version should be able to handle very long utterances.

I will test it locally to see whether it is reproducible.

**Comment by ngoel17** [comment]
It appears that the streaming server expects to know the length of audio upfront. That's not fair. It could be any unknown value from seconds to days.

**Comment by csukuangfj** [comment]
> It appears that the streaming server expects to know the length of audio upfront. 

What do you mean by this?

What the server needs to know is the number of samples in the current packet, which is set by the client
when the client sends the samples.

**Comment by ngoel17** [comment]
Perfect. I see that now. Why not use the buffer length? It could actually cause an overhead, for example, someone could choose 4096 samples thinking that it's a perfect power of 2, but you send an extra packet because you are unnecessarily sending the length. The packet length is kind of obvious from the packet. No need to transmit that.

**Comment by csukuangfj** [comment]
Thanks!

I thought websocket was a byte stream based protocol, so I need to send the length to figure out the boundary, though the length and the payload can be sent in a single packet.

https://stackoverflow.com/questions/47122719/whats-the-difference-between-websocket-fragmentation-and-tcp-fragmentation
says websocket is a message-based protocol. Whatever the client sends, it is received by the server in whole without fragmentation.

I will change it. We don't need the length.

**Comment by ngoel17** [comment]
Oh, another thing. The final "Done" message should go as a text message. On the server-side, binary messages should be passed for decoding and text messages should be parsed for commands. if you embed the text response and text requests in JSON, that will also allow you to return word timings, confidences, etc in the future (timing is often quite important for downstream tasks such as punctuation),  and to send additional items in the future such as hot words list, or speaker name (if the decoder is speaker adaptive) - https://websockets.readthedocs.io/en/2.2/_modules/websockets/protocol.html#WebSocketCommonProtocol.send

**Comment by csukuangfj** [comment]
Thanks! The link is very helpful.

**Comment by ngoel17** [comment]
> The issue is with the streaming server, and with the latest #22 version. The audio should be long (10 min or more) to replicate the issue.
  Here are the logs at the time of failure. Takes about 40 seconds to fail (whatever amount of audio is processed in 40 seconds, because the streaming client sends data at full blast). I tried introducing ping_interval=None, ping_timeout=None,
but that leads to a different problem that the client never disconnects. 

Now there is one other issue with ping_timeout. If the client goes away, the server does not drop the connections count. So the connections count keeps increasing...  Server-side logs (including the second connection after that) are right below client logs. 
-------------------------------
Traceback (most recent call last):
  File "/mnt/dsk4/sherpa/./sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_client.py", line 146, in <module>
    asyncio.run(main())
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/mnt/dsk4/sherpa/./sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_client.py", line 127, in main
    await run(server_addr, server_port, test_wav)
  File "/mnt/dsk4/sherpa/./sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_client.py", line 111, in run
    decoding_results = await receive_task
  File "/mnt/dsk4/sherpa/./sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_client.py", line 71, in receive_results
    async for message in socket:
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 482, in __aiter__
    yield await self.recv()
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 553, in recv
    await self.ensure_open()
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 930, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: received 1011 (unexpected error) keepalive ping timeout; then sent 1011 (unexpected error) keepalive ping timeout
-------------------------
2022-06-14 15:45:17,193 ERROR [server.py:234] connection handler failed
Traceback (most recent call last):
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 956, in transfer_data
    await asyncio.shield(self._put_message_waiter)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/websockets/legacy/server.py", line 232, in handler
    await self.ws_handler(self)
  File "/mnt/dsk4/sherpa/./sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_server.py", line 408, in handle_connection
    await socket.send(
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 620, in send
    await self.ensure_open()
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 930, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
2022-06-14 15:45:17,194 INFO [server.py:260] connection closed
2022-06-14 15:50:51,893 INFO [server.py:642] connection open
2022-06-14 15:50:51,893 INFO [streaming_server.py:385] Connected: ('127.0.0.1', 46950). Number of connections: 2/500

**Comment by csukuangfj** [comment]
> Here are the logs at the time of failure. Takes about 40 seconds to fail 

Does the issue still exist in the latest master?

**Comment by ngoel17** [comment]
It's caused more due to ping-pong not happening, and when the client streams packets with a 0.25 sec sleep in between, the connection stays alive.

**Comment by ngoel17** [comment]
From what I understood, https://github.com/k2-fsa/sherpa/issues/30 was fixed through better memory management, and endpointing is no longer needed in your opinion. Someone could still use it if they want to skip silence for computational purposes, but that would be their design choice. Should I close this issue?

**Comment by ngoel17** [comment]
As I said, once the sleep statement is there in the client, the client is
constantly informing the server-side that it's alive by periodically
sending data, and then the ping-pong timeout-based connection closing does
not happen as long as the connection is decent.

**Comment by ngoel17** [comment]
Resolved with 1.0
