### ISSUE TITLE
Sending a lot of request at the same time

### ISSUE THREAD

**Issue by EmreOzkose** [k2-fsa/sherpa#20]
When I run server with 

```
sherpa/bin/offline_server.py \
  --port 6006 \
  --num-device 0 \
  --max-batch-size 10 \
  --max-wait-ms 5 \
  --feature-extractor-pool-size 5 \
  --nn-pool-size 1 \
  --nn-model-filename ./path/to/exp/cpu_jit.pt \
  --bpe-model-filename ./path/to/data/lang_bpe_500/bpe.model
```
and client with 
```
./sherpa/bin/offline_client.py \
    --server-addr localhost \
    --server-port 6006 \
    /path/to/example1.wav
```

It works for single record very well. However when I send a lot of request at the same time, RAM become full and script is freezing. Did anyone face with this ? Do you have any advise for this situation?

**Comment by csukuangfj** [comment]
Do you have GPU?
You can change `--num-device 0` to `--num-device 1` or `--num-device 2` if you have multiple GPUs.

**Comment by csukuangfj** [comment]
The colab notebook https://colab.research.google.com/drive/1JX5Ph2onYm1ZjNP_94eGqZ-DIRMLlIca?usp=sharing
is using 50 connections and it works like a charm.

**Comment by csukuangfj** [comment]
Form the command you posted, it is `--num-device 0`.
Does it work well for `--num-device=1` for multiple requests?

**Comment by csukuangfj** [comment]
How many requests are you sending at the same time? 
You can use `--max-active-connections=100` to limit the number of active connections to 100 to avoid the server being overloaded if you don't have enough resources to handle more than 100 connections.

**Comment by EmreOzkose** [comment]
Thank you. I was using previous version which doesn't have `--max-active-connections=100` argument.

**Comment by EmreOzkose** [comment]
> 

Yes, I tried , it is slow, but works. GPU memory is the issue, but it can be limited with `--max-active-connections=100`, thank you.

**Comment by ahazned** [comment]
Hi,

Adding "with torch.no_grad():" before calling the models encoder decreases the GPU ram usage from >24GB to 2.5GB when there are 200 concurrent requests.

https://github.com/k2-fsa/sherpa/blob/522884ead319f32855026ea3a811f836cebe7488/sherpa/bin/offline_server.py#L191

**Comment by csukuangfj** [comment]
> Hi,
> 
> 
> 
> In our trials adding "with torch.no_grad():" before calling the model's encoder decreased the GPU ram usage from >24GB to 2.5GB when there are 200 concurrent requests.
> 
> 
> 
> https://github.com/k2-fsa/sherpa/blob/522884ead319f32855026ea3a811f836cebe7488/sherpa/bin/offline_server.py#L191

Thanks! 
Would you mind making a PR to fix it? 
Using the decorator "@torch.no_grad()" to the whole function may be more appropriate.

I set requires_grad of all parameters to False when exporting the model to torchscript. That's why I don't have such an issue.
