### ISSUE TITLE
can't build the sherpa

### ISSUE THREAD

**Issue by moodeerf** [k2-fsa/sherpa#205]
Hi,When I build the sherpa according to the READ.md, I get the following errors. I have already installed the k2.

![image](https://user-images.githubusercontent.com/43941697/201805755-1f06d69d-5669-4fb5-8b92-cf3f8e27d7f5.png)

**Comment by csukuangfj** [comment]
@moodeerf 

Please post the complete error logs.

**Comment by moodeerf** [comment]
> 

![image](https://user-images.githubusercontent.com/43941697/201813151-deb6c502-a41e-46b1-baa6-d4bbca3cf08d.png)

**Comment by csukuangfj** [comment]
What is the output of 
```
python3 -m k2.version
```

Are you using the latest k2, i.e, v1.22?

**Comment by moodeerf** [comment]
> 
@csukuangfj  thank you
![image](https://user-images.githubusercontent.com/43941697/201813098-ef01d622-9d61-4fa0-b8b8-a4ad6ae8056a.png)

**Comment by moodeerf** [comment]
> python3 -m k2.version

![image](https://user-images.githubusercontent.com/43941697/201813617-fc40c8b4-eb42-41cc-bbb2-b37f602d1ad8.png)

**Comment by csukuangfj** [comment]
@moodeerf 
Please update your k2 to v1.22.

You are using v1.21 at present.

**Comment by moodeerf** [comment]
@csukuangfj I update the k2 code ,but whe I build it , I get this error 
![image](https://user-images.githubusercontent.com/43941697/201816415-231f0d4c-0fe8-49b1-bf03-21f5f1fcdbb8.png)
^_^

**Comment by csukuangfj** [comment]
> @csukuangfj I update the k2 code ,but whe I build it , I get this error ![image](https://user-images.githubusercontent.com/43941697/201816415-231f0d4c-0fe8-49b1-bf03-21f5f1fcdbb8.png) ^_^

That is [an issue](https://github.com/pytorch/pytorch/issues/88290) from torch 1.12.x.

The fix is to run
```
cd /path/to/k2
python3 scripts/github_actions/fix_torch.py
```

(If you are using `python3 setup.py install`, it should run the above command automatically for you).

**Comment by moodeerf** [comment]
I can build the sherpa, thank you for your response ^-^
