### ISSUE TITLE
question about arg compute-cer 

### ISSUE THREAD

**Issue by yuekaizhang** [k2-fsa/sherpa#212]
According to https://github.com/k2-fsa/icefall/blob/master/icefall/utils.py#L425, https://github.com/k2-fsa/sherpa/blob/master/sherpa/bin/pruned_transducer_statelessX/decode_manifest.py#L130 should also save cut_id. args.compute-cer seems useless.

**Comment by csukuangfj** [comment]
> should also save cut_id.

Yes, you are right. Could you make a PR to fix it?

---

> args.compute-cer seems useless.

I think `args.compute-cer` is for Chinese dataset.

**Comment by yuekaizhang** [comment]
> > should also save cut_id.
> 
> Yes, you are right. Could you make a PR to fix it?
> 
> > args.compute-cer seems useless.
> 
> I think `args.compute-cer` is for Chinese dataset.

Okay, I would fix it.
