### ISSUE TITLE
in sherpa-online-websocket-server some options don't reach the correct module

### ISSUE THREAD

**Issue by ngoel17** [k2-fsa/sherpa#224]
Consider lower-level module options such as --dither or --use-gpu that are accepted but don't change anything.  This brings up anothre issue. The service contains multiple modules, and probably modules should have prefixes, so that we know on the top level which module the option belongs to. 
for example, the code also invokes the endpoint module, but the options for that module are never exported. It will be helpful if each module is included in a standard way, and then the option looks like:
   or.fe.dither  (module online-recognizer -> feature-extractor -> dither)
   or.ep.rule2.min-trailing-silence ( module online recognizer -> endpointer -> min-trailing-silence ).

  very similar to how Kaldi allows parse-options to register a prefix.

**Comment by csukuangfj** [comment]
@ngoel17 
Thanks for the suggestions. It is very helpful.

**Comment by ngoel17** [comment]
those specific examples work. so closing.
