### ISSUE TITLE
Zipformer Support

### ISSUE THREAD

**Issue by userasrk2** [k2-fsa/sherpa#252]
Hi guys,

Is the Zipformer model compatible with the current Sherpa version? If not is there a plan to support it?

Thanks,

**Comment by csukuangfj** [comment]
Yes, it is supported by sherpa.

Please have a look at
- https://k2-fsa.github.io/sherpa/cpp/pretrained_models/offline_transducer.html#icefall-asr-librispeech-pruned-transducer-stateless7-2022-11-11
- https://k2-fsa.github.io/sherpa/cpp/pretrained_models/offline_transducer.html#icefall-asr-librispeech-pruned-transducer-stateless8-2022-11-14
- https://k2-fsa.github.io/sherpa/cpp/pretrained_models/offline_transducer.html#icefall-asr-librispeech-pruned-transducer-stateless8-2022-12-02

The above 3 models are all of type zipformer

**Comment by csukuangfj** [comment]
If you want to use Python APIs, please use
https://github.com/k2-fsa/sherpa/tree/master/sherpa/bin/pruned_transducer_statelessX

**Comment by userasrk2** [comment]
Thanks @csukuangfj  really appreciate this.
