### ISSUE TITLE
Reading Zipformer model using Python API (Pybind11)

### ISSUE THREAD

**Issue by behnamasefi** [k2-fsa/sherpa#254]
Hi,

I'm trying to use the Pybind11 [bindings](https://github.com/k2-fsa/sherpa/tree/master/sherpa/python/csrc) to read a Zipformer model from Python code. I'm using pre-trained LibriSpeech models from [here](https://huggingface.co/csukuangfj/icefall-asr-librispeech-pruned-transducer-stateless7-2022-11-11) and it works fine with `sherpa-offline` C++ executable.

I have this very simple Python code to read the same model to the memory and create an instance of `OfflineRecognizer`:

```python
from sherpa import OfflineRecognizer, OfflineRecognizerConfig
import torch

torch._C._jit_set_profiling_executor(False)
torch._C._jit_set_profiling_mode(False)
torch._C._set_graph_executor_optimize(False)
torch.set_num_threads(1)
torch.set_num_interop_threads(1)

recognizer_config = OfflineRecognizerConfig(
    nn_model="/libri_model/icefall-asr-librispeech-pruned-transducer-stateless7-2022-11-11/exp/cpu_jit-epoch-30-avg-9-torch-1.10.0.pt",
    tokens="/libri_model/icefall-asr-librispeech-pruned-transducer-stateless7-2022-11-11/data/lang_bpe_500/tokens.txt"
)

recognizer = OfflineRecognizer(recognizer_config)
``` 

This is the error which I get with running that Python code:

```bash
[W tensor_numpy.cpp:77] Warning: Failed to initialize NumPy: No module named 'numpy' (function operator())
[I] /sherpa/sherpa/cpp_api/offline-recognizer-transducer-impl.h:127:void sherpa::OfflineRecognizerTransducerImpl::WarmUp() 2022-12-20 20:33:58 WarmUp begins
Traceback (most recent call last):
  File "/data/ourea/ourea/decode/sherpa_decoder.py", line 15, in <module>
    recognizer = OfflineRecognizer(recognizer_config)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/zipformer.py", line 23, in forward
    _0 = __torch__.icefall.utils.make_pad_mask
    encoder_embed = self.encoder_embed
    x0 = (encoder_embed).forward(x, )
          ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    x1 = torch.permute(x0, [1, 0, 2])
    lengths = torch.__rshift__(torch.sub(x_lens, 7), 1)
  File "code/__torch__/zipformer.py", line 173, in forward
    out = self.out
    _34 = torch.reshape(torch.transpose(x15, 1, 2), [b, t, torch.mul(c, f)])
    x16 = (out).forward(_34, )
           ~~~~~~~~~~~~ <--- HERE
    dropout = self.dropout
    return (dropout).forward(x16, )
  File "code/__torch__/torch/nn/modules/linear.py", line 23, in forward
    weight = self.weight
    bias = self.bias
    return _0(input, weight, bias, )
           ~~ <--- HERE
  File "code/__torch__/torch/nn/functional.py", line 4, in linear
    weight: Tensor,
    bias: Optional[Tensor]=None) -> Tensor:
  return torch.linear(input, weight, bias)
         ~~~~~~~~~~~~ <--- HERE
def dropout(input: Tensor,
    p: float=0.5,

Traceback of TorchScript, original code (most recent call last):
  File "/k2-dev/fangjun/open-source/icefall-dan-first/egs/librispeech/ASR/pruned_transducer_stateless7/zipformer.py", line 263, in forward
              of frames in `embeddings` before padding.
        """
        x = self.encoder_embed(x)
            ~~~~~~~~~~~~~~~~~~ <--- HERE

        x = x.permute(1, 0, 2)  # (N, T, C) -> (T, N, C)
  File "/k2-dev/fangjun/open-source/icefall-dan-first/egs/librispeech/ASR/pruned_transducer_stateless7/zipformer.py", line 1672, in forward
        # Now x is of shape (N, odim, (T-7)//2, ((idim-1)//2 - 1)//2)
        b, c, t, f = x.size()
        x = self.out(x.transpose(1, 2).reshape(b, t, c * f))
            ~~~~~~~~ <--- HERE
        # Now x is of shape (N, (T-7)//2, odim)
        x = self.dropout(x)
  File "/ceph-fj/fangjun/software/py38/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 103, in forward
    def forward(self, input: Tensor) -> Tensor:
        return F.linear(input, self.weight, self.bias)
               ~~~~~~~~ <--- HERE
  File "/ceph-fj/fangjun/software/py38/lib/python3.8/site-packages/torch/nn/functional.py", line 1848, in linear
    if has_torch_function_variadic(input, weight, bias):
        return handle_torch_function(linear, (input, weight, bias), input, weight, bias=bias)
    return torch._C._nn.linear(input, weight, bias)
           ~~~~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (95x640 and 2432x384)
```

Any idea what could be the issue?

Thanks,

**Comment by csukuangfj** [comment]
Could you try the following code?

That is, you have to specify the `FeatureConfig` to set the num_bins to 80.

https://github.com/k2-fsa/sherpa/blob/974a7ce70389fde207f9afcbe58693db290f6982/sherpa/python/test/test_offline_recognizer.py#L33-L46

**Comment by csukuangfj** [comment]
I suggest that you have a look at https://github.com/k2-fsa/sherpa/blob/master/sherpa/python/test/test_offline_recognizer.py#L33
and also read the documentation at 
https://k2-fsa.github.io/sherpa/cpp/pretrained_models/index.html

![Screenshot 2022-12-21 at 09 22 31](https://user-images.githubusercontent.com/5284924/208798394-49870120-8116-414d-9eea-3d688d6b1233.png)

**Comment by ravi-mr** [comment]
I tried with the latest clones of K2, Icefall, Lhotse and Sherpa. I am experiencing the same with **pruned_transducer_stateless7** model.
I have changed sampling frequency to 8000 and feat-dim to 40, even then I am seeing same failure.

Traceback (most recent call last):
  File "./sherpa/bin/offline_transducer_asr.py", line 368, in <module>
    main()
  File "./sherpa/bin/offline_transducer_asr.py", line 324, in main
    recognizer = create_recognizer(args)
  File "./sherpa/bin/offline_transducer_asr.py", line 314, in create_recognizer
    recognizer = sherpa.OfflineRecognizer(config)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/zipformer.py", line 23, in forward
    _0 = __torch__.icefall.utils.make_pad_mask
    encoder_embed = self.encoder_embed
    x0 = (encoder_embed).forward(x, )
          ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    x1 = torch.permute(x0, [1, 0, 2])
    lengths = torch.__rshift__(torch.sub(x_lens, 7), 1)
  File "code/__torch__/zipformer.py", line 173, in forward
    out = self.out
    _35 = torch.reshape(torch.transpose(x15, 1, 2), [b, t, torch.mul(c, f)])
    x16 = (out).forward(_35, )
           ~~~~~~~~~~~~ <--- HERE
    dropout = self.dropout
    return (dropout).forward(x16, )
  File "code/__torch__/torch/nn/modules/linear.py", line 22, in forward
    weight = self.weight
    bias = self.bias
    return torch.linear(input, weight, bias)
           ~~~~~~~~~~~~ <--- HERE

Traceback of TorchScript, original code (most recent call last):
  File "/root/k2-fsa_20230107/icefall/egs/ta-in/ASR/pruned_transducer_stateless7/zipformer.py", line 278, in forward
              of frames in `embeddings` before padding.
        """
        x = self.encoder_embed(x)
            ~~~~~~~~~~~~~~~~~~ <--- HERE
    
        x = x.permute(1, 0, 2)  # (N, T, C) -> (T, N, C)
  File "/root/k2-fsa_20230107/icefall/egs/ta-in/ASR/pruned_transducer_stateless7/zipformer.py", line 1709, in forward
        # Now x is of shape (N, odim, (T-7)//2, ((idim-1)//2 - 1)//2)
        b, c, t, f = x.size()
        x = self.out(x.transpose(1, 2).reshape(b, t, c * f))
            ~~~~~~~~ <--- HERE
        # Now x is of shape (N, (T-7)//2, odim)
        x = self.dropout(x)
  File "/root/k2-fsa_20230107/venv/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    def forward(self, input: Tensor) -> Tensor:
        return F.linear(input, self.weight, self.bias)
               ~~~~~~~~ <--- HERE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (95x2432 and 1152x384)


Can anyone help on this?

**Comment by csukuangfj** [comment]
Could you please show us the code you are using to load the model?

**Comment by ravi-mr** [comment]
@csukuangfj  I am using offline_transcriber like this,

python ./sherpa/bin/offline_transducer_asr.py  \
  --nn-model=/root/k2-fsa_20230107/icefall/egs/custom/ASR/pruned_transducer_stateless7/exp/cpu_jit.pt \
  --tokens=/root/k2-fsa_20230107/icefall/egs/custom/ASR/data/lang_bpe_500/tokens.txt \
  --decoding-method=greedy_search \
  --use-gpu=false \
  /asr_corpus/wav-8k/A000000?.wav

**Comment by csukuangfj** [comment]
> @csukuangfj I am using offline_transcriber like this,
> 
> `python ./sherpa/bin/offline_transducer_asr.py --nn-model=/root/k2-fsa_20230107/icefall/egs/custom/ASR/pruned_transducer_stateless7/exp/cpu_jit.pt --tokens=/root/k2-fsa_20230107/icefall/egs/custom/ASR/data/lang_bpe_500/tokens.txt --decoding-method=greedy_search --use-gpu=false /asr_corpus/wav-8k/A000000?.wav`

please have a look at https://github.com/k2-fsa/sherpa/pull/299 . It has been merged into the master.

----

You need to use
```bash
python ./sherpa/bin/offline_transducer_asr.py  \
  --nn-model=/root/k2-fsa_20230107/icefall/egs/custom/ASR/pruned_transducer_stateless7/exp/cpu_jit.pt \
  --tokens=/root/k2-fsa_20230107/icefall/egs/custom/ASR/data/lang_bpe_500/tokens.txt \
  --decoding-method=greedy_search \
  --use-gpu=false \
  --sample-rate=8000 \
  --feat-dim 40 \
  /asr_corpus/wav-8k/A000000?.wav
```

**Comment by ravi-mr** [comment]
and it throws, 

`offline_transducer_asr.py: error: unrecognized arguments: --sample-rate=8000 --feat-dim
`

**Comment by csukuangfj** [comment]
> and it throws,
> 
> `offline_transducer_asr.py: error: unrecognized arguments: --sample-rate=8000 --feat-dim `

Have you updated your sherpa to the latest master?

**Comment by csukuangfj** [comment]
> offline_transducer_asr.py: error: unrecognized arguments: --sample-rate=8000 --feat-dim 

these two arguments were introduced in #299 , which was merged into the master about an hour ago.

**Comment by ravi-mr** [comment]
That works!!!

**Comment by ravi-mr** [comment]
Guess Sherpa binaries also require these changes

**Comment by csukuangfj** [comment]
> Guess Sherpa binaries also require these changes

The C++ binaries already support that.
```
 ./bin/sherpa-offline
```

It will show the following help output (0nly part of them is posted here)
```
  --sample-frequency          : Waveform data sample frequency (must match the waveform file, if specified there) (float, default = 16000)
  --num-mel-bins              : Number of triangular mel-frequency bins (int, default = 80)
```
