### ISSUE TITLE
comment error

### ISSUE THREAD

**Issue by Innocence-0712** [k2-fsa/sherpa#274]
https://github.com/k2-fsa/sherpa/blob/927a99c9212dfb359777bf86c3211e145f7d0e75/sherpa/cpp_api/bin/offline-recognizer.cc#L50
https://github.com/k2-fsa/sherpa/blob/927a99c9212dfb359777bf86c3211e145f7d0e75/sherpa/cpp_api/bin/offline-recognizer.cc#L60

Hi, all
        The above should be modify to true. The inner C++ code wanna true in the two decode mode also.
Thx.

**Comment by csukuangfj** [comment]
@Innocence-0712 
Yes, you are right.

Would you mind making a pull-request to fix it? Thanks!

**Comment by Innocence-0712** [comment]
Ok, Jun brother (军哥), I have made the pr. https://github.com/k2-fsa/sherpa/pull/275

**Comment by Innocence-0712** [comment]
> @Innocence-0712 Yes, you are right.
> 
> Would you mind making a pull-request to fix it? Thanks!

You are welcome.
Ok, Jun brother (军哥), I have made the pr. https://github.com/k2-fsa/sherpa/pull/275

**Comment by Innocence-0712** [comment]
@csukuangfj You are welcome.
Ok, Jun brother (军哥), I have made the pr. https://github.com/k2-fsa/sherpa/pull/275

**Comment by csukuangfj** [comment]
Closing via #275
