### ISSUE TITLE
Streaming Zipformer crashing sherpa

### ISSUE THREAD

**Issue by maltium** [k2-fsa/sherpa#287]
Using _cpu_jit.pt_ and _bpe.model_ available at https://huggingface.co/Zengwei/icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29 is crashing sherpa for me. I've tested the offline version of zipformer and it works fine.

Sherpa is built locally from commit 21a5b943.

I'm attaching an image from the console showing the error to preserve formatting.

![image](https://user-images.githubusercontent.com/4674453/212535601-b05dcdd9-1bee-429b-8f0f-618aaf77c08d.png)

**Comment by csukuangfj** [comment]
Sorry, I am afraid that Python script does work with streaming zipformer.
We will fix it shortly, but you can first try the c++ binary `sherpa-online`, which you can find its usage
when you download the model, e.g., from

https://k2-fsa.github.io/sherpa/cpp/pretrained_models/online_transducer.html#icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29

If you want to use a sever/client architecture, please replace `sherpa-online` with `sherpa-online-websocket-server`,
which provides exactly the same functionality as `streaming_server.py`.

**Comment by maltium** [comment]
`sherpa-online` requires `encoder_jit_trace.pt`, `decoder_jit_trace.pt` and `joiner_jit_trace.pt` unlike the Python script counterpart. When I tried to export them by running the `jit_trace_export.py` script, the export failed with this error.

![image](https://user-images.githubusercontent.com/4674453/212833569-169c3f5a-e5de-4864-a712-e3e60bbb6937.png)
