### ISSUE TITLE
Run streaming ASR server on GPU

### ISSUE THREAD

**Issue by YuriiMytiai** [k2-fsa/sherpa#288]
Hello,
I'm wondering if there any expected advantages in terms of RTF/latency when running streaming server on GPU with single client?

I've compared latency and accuracy on CPU and GPU for `librispeech-pruned-stateless-streaming-conformer-rnnt4` pretrained model with a `greedy search`, and in my experiment there's no advantages on running streaming server with a single client on the GPU. 
I got even a bit worse latency when running server on GPU (mean latency _2.77 sec_ on CPU vs. _2.84 sec_ on GPU). 

The good thing is that "finalized" hypothesis (hypothesis on endpoints) are equal, so accuracy is the same. 

But I thought that there should be some benefits from running streaming server on GPU, because I saw that k2-fsa has possibility to run FST operations on GPU and in the streaming server code this is implemented. Probably I'll see difference when decode with `fast-beam-search with LM`? Or it is not expected that GPU will accelerate decoding and it is useful only for multi-client task?

Thanks!

**Comment by YuriiMytiai** [comment]
Update: indeed when running fast beam search with LG decoding the difference between latency on GPU and CPU are bigger, and GPU has lower values, but for most of my test audios this difference is not dramatic. I tested it with default decoder parameters

**Comment by csukuangfj** [comment]
1. Do you ignore the warmup time for the first request?  The first request needs more processing time.

2. If you only have 1 client, it is not cost-effective to use a GPU. The advantage of GPU is parallel processing, e.g., batch processing (handling multiple clients at the same time).

**Comment by YuriiMytiai** [comment]
1. I saw there's warm-up step with some random input when server starts. Isn't that enough to warm it up?
2. That's clear, I still want to understand if there's any benefit from running FST-related stuff on GPU

**Comment by csukuangfj** [comment]
> I saw there's warm-up step with some random input when server starts. Isn't that enough to warm it up?

Yes. It is better to ignore the first few requests when doing a benchmark.

**Comment by csukuangfj** [comment]
>  I still want to understand if there's any benefit from running FST-related stuff on GPU

If you only have one client or several clients, I think you won't benefit a lot from using GPU in decoding.

Maybe @danpovey has something to say about this.
