### ISSUE TITLE
Using beam search in offline server

### ISSUE THREAD

**Issue by ahazned** [k2-fsa/sherpa#29]
Hi,

Do you have any plans to add modified beam search to the offline server? I think it'd be worthwhile to get better offline accuracies than the current greedy search strategy.

**Comment by csukuangfj** [comment]
Yes, I am adding it. Will finish it today tomorrow.

**Comment by ahazned** [comment]
Ok thank you very much.

**Comment by csukuangfj** [comment]
@ahazned 
You can try https://github.com/k2-fsa/sherpa/pull/32, which requires https://github.com/k2-fsa/k2/pull/983

They are working now but lacking some documentation.

I am adding documentation and will merge them as soon as possible.

**Comment by ahazned** [comment]
@csukuangfj 

Thank you very much. I tried it and it works fine.
