### ISSUE TITLE
GPU memory grows over time for streaming emformer server

### ISSUE THREAD

**Issue by ngoel17** [k2-fsa/sherpa#30]
Take a 10 minute long or longer recording. To ensure that its close to realtime upload, you can insert the following command on line  102 https://github.com/k2-fsa/sherpa/blob/063f67f3fb5a25a2576273f7f0c1e5f24976ddd8/sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_client.py#L102 
 await asyncio.sleep(0.25)

 Then run the client and the server, and in a separate terminal issue the command "watch nvidia-smi" and monitor the memory usage.

**Comment by csukuangfj** [comment]
How many clients are you using and what are the commands you used to start the server?

**Comment by ngoel17** [comment]
1 client. 
./sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_server.py \
  --port 6007 \
  --max-batch-size 50 \
  --max-wait-ms 5 \
  --max-active-connections 500 \
  --nn-pool-size 1 \
  --nn-model-filename <model.pt> \
  --bpe-model-filename <data/lang_bpe_500/bpe.model>

**Comment by csukuangfj** [comment]
I am using
https://github.com/k2-fsa/sherpa/blob/e850f1d0d58a471b32b13a0218533d76f36ed1a7/sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_client.py#L94-L95

https://github.com/k2-fsa/sherpa/blob/e850f1d0d58a471b32b13a0218533d76f36ed1a7/sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_client.py#L105

in #40 

GitHub actions can decode sound files with different durations: 10 minutes, 20 minutes, and 30 minutes, without
any problems.
(Note: GitHub actions uses CPU)

I also tested it locally with GPU (V100 32GB). The GPU RAM usage is rather stable,  which is about 1721 MB.
(The server handles two connections concurrently: One connection sends a wave file of 30 minutes, while the other sends a 20-minute wave file)

**Comment by csukuangfj** [comment]
@ngoel17 
The latest master should fix this issue. Please leave a comment if it is still an issue for you.
