### ISSUE TITLE
Offline Transducer input limit

### ISSUE THREAD

**Issue by KazBrekker1** [k2-fsa/sherpa#322]
Is there a limit to the audio size passed to the offline_transducer_asr.py script?

I'm using modified_beam_search with beam _size 2 on cpu

**Comment by csukuangfj** [comment]
It is limited by the amount of CPU RAM you have.

**Comment by KazBrekker1** [comment]
When I run t
he scripts, only one CPU core gets utilized, is there an option to increase the number of CPUs used for the offline transducer?

**Comment by csukuangfj** [comment]
Yes, please change
https://github.com/k2-fsa/sherpa/blob/4756d4ec10c61164eff356190740527993844df3/sherpa/bin/offline_transducer_asr.py#L356-L357

**Comment by KazBrekker1** [comment]
ok that helped

Do you think it will be a good idea if these parameters  ` torch.set_num_threads` ` torch.set_num_interop_threads` get added to the argparse params?

Thank you.

**Comment by csukuangfj** [comment]
> ok that helped
> 
> Do you think it will be a good idea if these parameters ` torch.set_num_threads` ` torch.set_num_interop_threads` get added to the argparse params?
> 
> Thank you.

Sure. Would you mind creating a pull-request to add that?

**Comment by KazBrekker1** [comment]
Yes of course!
