### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by Text2-m** [k2-fsa/sherpa#324]
安装出现这个问题
<img width="671" alt="截屏2023-03-03 19 48 32" src="https://user-images.githubusercontent.com/37999223/222713198-93d6b420-a378-41a3-94ed-4060f24cc23b.png">

**Comment by csukuangfj** [comment]
可以给出完整的错误信息么？
还有，你的 gcc 是哪个版本呢？

**Comment by Text2-m** [comment]
> 可以给出完整的错误信息么？
> 还有，你的 gcc 是哪个版本呢？

gcc=7.5.0 
<img width="885" alt="截屏2023-03-06 10 22 21" src="https://user-images.githubusercontent.com/37999223/223005145-4c067285-3c79-4884-9cb3-5c8a2935d2f4.png">

**Comment by csukuangfj** [comment]
可以给出下面命令的 log 吗
```bash
rm CMakeCache.txt
cmake ..
```

还有，你系统上只有一个版本的 gcc 吗？

**Comment by Text2-m** [comment]
还有一个4.8的 个人用户是7.5

**Comment by Text2-m** [comment]
> 还有一个4.8的 个人用户是7.5
<img width="803" alt="截屏2023-03-06 10 33 57" src="https://user-images.githubusercontent.com/37999223/223006384-ebf1fc3a-c4a5-4bd1-b057-e321cc4580c7.png">

**Comment by csukuangfj** [comment]
> 可以给出下面命令的 log 吗
> 
> ```shell
> rm CMakeCache.txt
> cmake ..
> ```
> 

请帖这个命令的输出。不是 `make install/strip` 的 log.

(你贴了两次 `make install/strip` 的 log了，但现在不需要这个)

**Comment by Text2-m** [comment]
> > 可以给出下面命令的 log 吗
> > ```shell
> > rm CMakeCache.txt
> > cmake ..
> > ```
> 
> 请帖这个命令的输出。不是 `make install/strip` 的 log.
> 
> (你贴了两次 `make install/strip` 的 log了
<img width="1954" alt="iShot_2023-03-06_11 23 39" src="https://user-images.githubusercontent.com/37999223/223012651-c2ab1526-4b77-4862-a5bc-51aba635a7ac.png">
，但现在不需要这个)

**Comment by csukuangfj** [comment]
@Text2-m 

please read the first line of the log.

It is using gcc 4.8.5, not gcc 7.5.

You have two versions of GCC and you need to tell sherpa which one to use.

---

Please refer to
https://k2-fsa.github.io/k2/installation/faqs.html#error-c-14-or-later-compatible-compiler-is-required-to-use-aten
for how to set environment variables so that sherpa can find gcc 7.5

**Comment by Text2-m** [comment]
> @Text2-m
> 
> please read the first few lines of the log.
> 
> It is using gcc 4.8.5, not gcc 7.5.
> 
> You have two versions of GCC and you need to tell sherpa which one to use.
> 
> Please refer to https://k2-fsa.github.io/k2/installation/faqs.html#error-c-14-or-later-compatible-compiler-is-required-to-use-aten for how to set environment variables so that sherpa can find gcc 7.5

tahks
