### ISSUE TITLE
Install sherpa-onnx

### ISSUE THREAD

**Issue by alidabaghi** [k2-fsa/sherpa#341]
hello. i am trying to install sherpa-onnx and occurance this error?
![Screenshot from 2023-03-13 13-59-24](https://user-images.githubusercontent.com/78419335/224676604-450fa852-1b2b-420c-9df3-feea490150b5.png)

**Comment by csukuangfj** [comment]
Please post all the logs.

The logs you posted has very little information.

Also, which method are you using to install sherpa-onnx?

**Comment by AliDs2022** [comment]
thank you for answering.  I installed in yesterday.

**Comment by csukuangfj** [comment]
@AliDs2022 
Glad to hear that you have managed to install sherpa-onnx.

Could you tell us how you fixed the installation issue?

**Comment by alidabaghi** [comment]
hello.  I used to this documentaion. https://k2-fsa.github.io/sherpa/onnx/install/linux.html
but I didn't go to the sherpa-onnx directory after cloning.
