### ISSUE TITLE
test zipformer for front framework

### ISSUE THREAD

**Issue by alidabaghi** [k2-fsa/sherpa#357]
hello. i am trying test pruned_transducer_stateless7_streaming in streaming_server.py.
my goal is test stream for frontend framework?

**Comment by csukuangfj** [comment]
What is `frontend framework`?

And what issues do you have?

**Comment by alidabaghi** [comment]
Is this possible?

**Comment by csukuangfj** [comment]
> Is this possible?

Yes, that is perfectly possible.

Could you post any issues you currently have?

**Comment by csukuangfj** [comment]
> What I mean is test zipformer in "https://github.com/k2-fsa/sherpa/blob/master/sherpa/bin/streaming_pruned_transducer_statelessX/streaming_server.py" i have been tried to add zipformer model but can not ?

please see https://github.com/k2-fsa/sherpa/pull/365
