### ISSUE TITLE
Do you have any plan for build streaming CTC decoding model?

### ISSUE THREAD

**Issue by trangtv57** [k2-fsa/sherpa#366]
Tks @csukuangfj for build this project, 
I have a question about when you support add streaming CTC decoding in sherpa, I see that K2 already have CTC decoding streaming. So I just wonder?
Tks

**Comment by csukuangfj** [comment]
Yes, but not in the near future. We are busy with other stuff at present.

**Comment by trangtv57** [comment]
tks @csukuangfj
