### ISSUE TITLE
Any support for ctc guide decode with blank skip?

### ISSUE THREAD

**Issue by drawfish** [k2-fsa/sherpa#386]
It seem that currently shepra only add this feature for triton inference. Is there any plan for support for ctc guide decode with blank skip for transducer?

**Comment by csukuangfj** [comment]
> It seem that currently shepra only add this feature for triton inference. Is there any plan for support for ctc guide decode with blank skip for transducer?

We don't have time to add it to sherpa now, but we welcome contributions from the community.

**Comment by drawfish** [comment]
> > It seem that currently shepra only add this feature for triton inference. Is there any plan for support for ctc guide decode with blank skip for transducer?
> 
> We don't have time to add it to sherpa now, but we welcome contributions from the community.

I see. If I have time, I will add this. 
Well, this issue is related to another issue in [icefall](https://github.com/k2-fsa/icefall/pull/1080). How can I check if the export jit model is correct after I modified the code of the frame_reduce.py?

**Comment by yfyeung** [comment]
You can compare the output of frame_reducer.py between the old and your versions.

**Comment by yfyeung** [comment]
> It seem that currently shepra only add this feature for triton inference. Is there any plan for support for ctc guide decode with blank skip for transducer?

https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless7_ctc_bs/export_onnx.py This recipe support export blank-skip model for both onnx and triton.

**Comment by drawfish** [comment]
Good ~
