### ISSUE TITLE
install sherpa from master

### ISSUE THREAD

**Issue by alidabaghi123** [k2-fsa/sherpa#388]
hello. i have been tried to install new version of sherpa and occurance this error?
![Screenshot from 2023-05-30 11-00-37](https://github.com/k2-fsa/sherpa/assets/78419335/1adc7a51-50bc-4379-a8e2-30b9d6d5045f)

**Comment by csukuangfj** [comment]
@alidabaghi123 

Please try the latest master again. It should be fixed.
