### ISSUE TITLE
error in inference zipformer framework

### ISSUE THREAD

**Issue by alidabaghi123** [k2-fsa/sherpa#421]
hello. i worked with sherpa framework for zipformer streamin. some times disconned from server and show this error in terminal. why?
![Screenshot from 2023-07-01 14-57-18](https://github.com/k2-fsa/sherpa/assets/78419335/3a41ddf3-0040-410c-86c3-ff740bf67188)

**Comment by danpovey** [comment]
You should probably specify all software versions, especially torch versions and onnx versions if relevant, and the filenames of any of our uploaded models that you are using, as I suspect this may come down to a version mismatch of some kind.  (But Fangjun will know better).

**Comment by csukuangfj** [comment]
Could you please post your complete command and all the logs?

Also, please re-check that the given tokens.txt matches your model.

**Comment by alidabaghi123** [comment]
> You should probably specify all software versions, especially torch versions and onnx versions if relevant, and the filenames of any of our uploaded models that you are using, as I suspect this may come down to a version mismatch of some kind. (But Fangjun will know better).

Thank you very much.

**Comment by alidabaghi123** [comment]
> Could you please post your complete command and all the logs?
> 
> Also, please re-check that the given tokens.txt matches your model.

You should probably specify all software versions, especially torch versions and onnx versions if relevant, and the filenames of any of our uploaded models that you are using, as I suspect this may come down to a version mismatch of some kind. (But Fangjun will know better).

**Comment by csukuangfj** [comment]
Have you fixed it?

**Comment by alidabaghi123** [comment]
> Have you fixed it?

excuse me. I have updated comment.

**Comment by csukuangfj** [comment]
> excuse me. I have updated comment.

Please post all of the logs. That is, it should contain the logs since you start `streaming_server.py`. The logs should contain the output of 
https://github.com/k2-fsa/sherpa/blob/da5a7153fa972952d2d2fd01215053d23a6ecd7b/sherpa/bin/streaming_server.py#L780

---

Please give us as much information as you could.

**Comment by alidabaghi123** [comment]
> > excuse me. I have updated comment.
> 
> Please post all of the logs. That is, it should contain the logs since you start `streaming_server.py`. The logs should contain the output of
> 
> https://github.com/k2-fsa/sherpa/blob/da5a7153fa972952d2d2fd01215053d23a6ecd7b/sherpa/bin/streaming_server.py#L780
> 
> Please give us as much information as you could.

![Screenshot from 2023-07-02 11-12-22](https://github.com/k2-fsa/sherpa/assets/78419335/a4efa115-8d2e-4129-b91f-748e3112c3ba)
![Screenshot from 2023-07-02 11-13-10](https://github.com/k2-fsa/sherpa/assets/78419335/52e1104f-0ba1-444b-8d94-18a9291216fe)

**Comment by csukuangfj** [comment]
So the log shows it indeed returns decoded results to the client but throws an error at the end.

**Comment by csukuangfj** [comment]
Could you change
https://github.com/k2-fsa/sherpa/blob/da5a7153fa972952d2d2fd01215053d23a6ecd7b/sherpa/cpp_api/online-recognizer.cc#L189
to
```cpp
std::cerr << i << ", ";
 auto sym = sym_table[i]; 
std::cerr << sym<< "\n";
```

and re-compile sherpa and try again?

**Comment by alidabaghi123** [comment]
thank you. my problem is tokens.txt. and fixed it
