### ISSUE TITLE
triton中的启动路径不同和找不到模型

### ISSUE THREAD

**Issue by standyyyy** [k2-fsa/sherpa#424]
尝试根据教程 https://github.com/k2-fsa/sherpa/tree/master/triton
来启动triton服务 。

按照教程一步一步顺利启动了docker，只在挂载路径的时候改动成了绝对路径 。
在准备执行shell脚本的时候发现，该路径没有build_wenetspeech_pruned_transducer_stateless5_streaming.sh ，
脚本在scripts文件夹里面  ，不知道这里是不是文档没更新导致的，build_wenetspeech_pruned_transducer_stateless5_streaming.sh文件已经移到了scripts文件夹里面 。
cd scripts 之后 执行 
`bash build_wenetspeech_pruned_transducer_stateless5_streaming.sh `报了以下错
![image](https://github.com/k2-fsa/sherpa/assets/39285732/7eaa482c-06ab-4792-a010-36b7e65efcbc)

然后到退回triton路径中 ，执行以下代码，在执行脚本前面加上了scripts，
`bash scripts/build_wenetspeech_pruned_transducer_stateless5_streaming.sh`
一开始运行的时候报错了
`root@docker-desktop:/workspace/sherpa/triton# bash scripts/build_wenetspeech_pruned_transducer_stateless5_streaming.sh
pretrained model using char
skip download pretrained model
export onnx
/usr/bin/env: 'python3\r': No such file or directory
/workspace/sherpa/triton
auto gen config.pbtxt
cp: cannot stat '/workspace/icefall/egs/wenetspeech/ASR/icefall_asr_wenetspeech_pruned_transducer_stateless5_streaming/exp/encoder_fp16.onnx': No such file or directory
cp: cannot stat '/workspace/icefall/egs/wenetspeech/ASR/icefall_asr_wenetspeech_pruned_transducer_stateless5_streaming/exp/decoder_fp16.onnx': No such file or directory
cp: cannot stat '/workspace/icefall/egs/wenetspeech/ASR/icefall_asr_wenetspeech_pruned_transducer_stateless5_streaming/exp/joiner_fp16.onnx': No such file or directory`

![image](https://github.com/k2-fsa/sherpa/assets/39285732/8ebdb9a0-b1b2-4474-94d7-538a6997f447)

然后我确实去找了下，没有模型。
希望大佬帮忙看看是啥问题

**Comment by csukuangfj** [comment]
@yuekaizhang @wd929  可以帮忙看下不？

**Comment by yuekaizhang** [comment]
> 

你这里贴的不是最原始的报错信息。我试着跑了一下，应该是没装 Onnx 这个库，你拉一下 #426 这个 fix. 我本地测试是没问题了，如果再遇到问题可以把最开头的报错截图一下。
