### ISSUE TITLE
Need word timestamps

### ISSUE THREAD

**Issue by ngoel17** [k2-fsa/sherpa#43]
Information on word timestamps or at least the length of audio processed "till now" in the streaming server, will be helpful, both for downstream audio segmenting / alignment tasks and also for observing latencies under heavy load.

**Comment by csukuangfj** [comment]
> Information on word timestamps

I think this should be fairly easy to add. For each received frame, we can assign a BPE token to it.
To get the start timestamp of a word, we only need to get the start timestamp of the first BPE token of the word.
The first BPE token of a word starts with `_`.
The stop timestamp of a word is the timestamp of its last BPE token.
The frames between the end of a word and the start of the next word correspond to blanks and can be 
classified as silences.

Help from the community is very welcome.

If no one does that, I will implement it after the next week.
