### ISSUE TITLE
What type of benchmark is being run on the GPU  and CPU 

### ISSUE THREAD

**Issue by erquren** [k2-fsa/sherpa#453]
In this Web,i see the benchmark,but i cant see the cpu type and gpu type
it is run on v100?or other gpu

https://k2-fsa.github.io/sherpa/triton/trt/index.html#benchmark-for-conformer-trt-encoder-vs-onnx

**Comment by csukuangfj** [comment]
@yuekaizhang  Could you please help clarify it?

**Comment by yuekaizhang** [comment]
> In this Web,i see the benchmark,but i cant see the cpu type and gpu type it is run on v100?or other gpu
> 
> https://k2-fsa.github.io/sherpa/triton/trt/index.html#benchmark-for-conformer-trt-encoder-vs-onnx

Hi thanks, it ran on a single v100 both for onnx and trt.

**Comment by erquren** [comment]
> 

thank
