### ISSUE TITLE
While training got a error

### ISSUE THREAD

**Issue by SSwethaSel0609** [k2-fsa/sherpa#480]
I have installed k2 
But stillI'm getting error like no module found k2
 import k2
ModuleNotFoundError: No module named 'k2'

**Comment by csukuangfj** [comment]
Please describe how you installed k2 and please post the installation logs.

**Comment by SSwethaSel0609** [comment]
1. conda create -n icefall_env torchvision torchaudio pytorch-cuda=11.6 pytorch=1.13=py3.10_cuda11.6_cudnn8.3.2_0 k2 -c pytorch -c nvidia -c k2-fsa
2. conda activate icefall_env
3. pip install lhotse
4. sudo  git clone https://github.com/k2-fsa/icefall 
6.cd icefall
7. sudo pip install -r requirements.txt
8. sudo  pip install .
I tried again and now i got the new error like no module named icefall  File "/mnt/efs/swetha/marathi/ds-icefall-scripts/./pruned_transducer_stateless7/train.py", line 59, in <module>
    from asr_datamodule import AsrDataModule
  File "/mnt/efs/swetha/marathi/ds-icefall-scripts/pruned_transducer_stateless7/asr_datamodule.py", line 44, in <module>
    from icefall.utils import str2bool
ModuleNotFoundError: No module named 'icefall'

**Comment by csukuangfj** [comment]
Please follow the icefall installation. You forgot setting the environment variable PYTHONPATH.

**Comment by csukuangfj** [comment]
I strongly recommend you to read the doc before you continue. It will save you a lot of time.
