### ISSUE TITLE
请问一下Zipformer-transducer-based Models里面的预训练模型有官方测试结果吗？

### ISSUE THREAD

**Issue by HeroSong666** [k2-fsa/sherpa#485]
比如在XX数据集上面测试得到的WER为X%之类的？

**Comment by csukuangfj** [comment]
icefall 里面的每个 recipe 的 RESULTS.md ，有详细的 WER 数据。

**Comment by HeroSong666** [comment]
> icefall 里面的每个 recipe 的 RESULTS.md ，有详细的 WER 数据。

我找了一下，好像其他模型的都有，唯独Zipformer的结果好像没有？

**Comment by csukuangfj** [comment]
> 唯独Zipformer的结果好像没有

你只的具体是哪个模型？请贴完整的模型文件夹名字。

**Comment by HeroSong666** [comment]
只有icefall提供的模型有测试结果的数据吗？您（[csukuangfj]）提供的模型，比如[csukuangfj/sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13 (Bilingual, Chinese + English)]没有测试结果的数据吗？

**Comment by HeroSong666** [comment]
> > 唯独Zipformer的结果好像没有
> 
> 你只的具体是哪个模型？请贴完整的模型文件夹名字。

只有icefall提供的模型有测试结果的数据吗？您（[csukuangfj]）提供的模型，比如[csukuangfj/sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13 (Bilingual, Chinese + English)]有没有测试结果的数据呢？

**Comment by csukuangfj** [comment]
![Screenshot 2023-10-12 at 15 03 11](https://github.com/k2-fsa/sherpa/assets/5284924/8ea48c8d-d083-4263-8bea-6a4270080ba0)


<img width="797" alt="Screenshot 2023-10-12 at 15 03 57" src="https://github.com/k2-fsa/sherpa/assets/5284924/2cb911ea-3aeb-4cf8-9bcc-47602b970f47">

TEST_NET TEST_MEETING 是 wenetspeech 里面的测试集

**Comment by HeroSong666** [comment]
谢谢！
