### ISSUE TITLE
[Help is wanted] Run sherpa from browser on Huggingface

### ISSUE THREAD

**Issue by csukuangfj** [k2-fsa/sherpa#50]
In the following screenshot,
https://huggingface.co/speechbrain/asr-transformer-transformerlm-librispeech

A user can click the button "Record from browser" to record his/her voice and then click  the button "Compute", which
will run the model to decode the speech and displays the decoded results.

It is nice to also have it with sherpa.

![90a](https://user-images.githubusercontent.com/5284924/177508456-08fa37b9-de01-43d4-86d5-38a39b8ce585.png)

**Comment by jtrmal** [comment]
I might look at it if you have some pointers on how to get started?
y.

**Comment by csukuangfj** [comment]
@jtrmal 

As a first step, I recommend you to visit https://github.com/huggingface/api-inference-community

That repository contains examples about using [ESPnet](https://github.com/espnet/espnet), [NeMo](https://github.com/NVIDIA/NeMo), and [Speechbrain](https://github.com/speechbrain/speechbrain) for automatic speech recognition.

The [README.md](https://github.com/huggingface/api-inference-community/blob/main/README.md) in the above
repository contains instructions for how to add a new library.

Basically, you need to create a directory `docker_imsages/k2` inside the above repo and copy everything from the directory [docker_images/common](https://github.com/huggingface/api-inference-community/tree/main/docker_images/common) to it and then start to modify things.

(Note: We can also use the name `docker_images/sherpa`, or `docker_images/icefall`. You can decide the name to use.)

I have good news for you. You can use the PR [Add support for NeMo](https://github.com/huggingface/api-inference-community/pull/35) as a concrete example.

After finishing adding `docker_imsages/k2` and getting merged, you may wonder how to access it over <https://huggingface.co>.

You can use the following three URLs to find all models on huggingface that are using automatic speech recognition from the above repository:
- https://huggingface.co/models?library=espnet&pipeline_tag=automatic-speech-recognition
- https://huggingface.co/models?library=nemo&pipeline_tag=automatic-speech-recognition
- https://huggingface.co/models?library=speechbrain&pipeline_tag=automatic-speech-recognition

Note: The above three URLs differ only in the parameter `library`. Once you fix this issue, you can also use
https://huggingface.co/models?library=k2&pipeline_tag=automatic-speech-recognition
to find all models on huggingface that are using k2 for ASR. (Assuming you choose `docker_images/k2`).

Let us click https://huggingface.co/models?library=nemo&pipeline_tag=automatic-speech-recognition
and you will see the following screenshot:
<img width="1037" alt="Screen Shot 2022-07-07 at 12 42 21 PM" src="https://user-images.githubusercontent.com/5284924/177692915-488301be-1d8e-4be0-a5c9-ff75545eaa2f.png">

If we click the first model, i.e., visit https://huggingface.co/nvidia/stt_en_conformer_transducer_xlarge , we will see
the following screenshot:
![0b0a](https://user-images.githubusercontent.com/5284924/177693204-0e4c45f5-b1e3-4be6-a9c2-9a1ca9c4e993.png)

Click `Edit model card` (or click `Files and versions` and click the file `README.md`), and you will see:
![0a0b12](https://user-images.githubusercontent.com/5284924/177693504-2b46209b-1607-4eb5-8934-b89e02b21097.png)
 
The most important three lines are
```md
library_name: nemo
tags:
- automatic-speech-recognition
```

`library_name: nemo` means it selects [docker_images/nemo](https://github.com/huggingface/api-inference-community/tree/main/docker_images/nemo)

The tag `automatic-speech-recognition` means to select the pipeline
https://github.com/huggingface/api-inference-community/blob/main/docker_images/nemo/app/pipelines/automatic_speech_recognition.py
(Note it replaces `-` with `_` internally).

I have added the following lines to
https://huggingface.co/csukuangfj/icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/blob/main/README.md

```md
---
language:
- en
library_name: k2
tags:
- automatic-speech-recognition
widget:
- example_title: Librispeech sample 1
  src: https://huggingface.co/csukuangfj/icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/resolve/main/test_wavs/1089-134686-0001.wav
- example_title: Librispeech sample 2
  src: https://huggingface.co/csukuangfj/icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/resolve/main/test_wavs/1221-135766-0001.wav
- example_title: Librispeech sample 3
  src: https://huggingface.co/csukuangfj/icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/resolve/main/test_wavs/1221-135766-0002.wav
---
```
and it produces the following screenshot
<img width="1299" alt="Screen Shot 2022-07-07 at 1 00 18 PM" src="https://user-images.githubusercontent.com/5284924/177694923-c2fb875a-8880-4032-8875-5c3ca3c94ca9.png">

However, if you click the `Compute` button, it will display `Internal Server Error`.

Hope that if you finish adding `docker_images/k2` to https://github.com/huggingface/api-inference-community, it will work.

Thanks!

**Comment by jtrmal** [comment]
nice, thank you!
will start working on it this week
y.

**Comment by jtrmal** [comment]
do you want me to install sherpa always from git or do you prefer from pip?
I mean for the huggingface docker image build
y.

**Comment by jtrmal** [comment]
So far I have this:
https://github.com/huggingface/api-inference-community/compare/main...jtrmal:k2_sherpa?expand=1

should be pretty much complete, only initiation and running the decoder remains to be implemented

**Comment by csukuangfj** [comment]
> So far I have this: https://github.com/huggingface/api-inference-community/compare/main...jtrmal:k2_sherpa?expand=1
> 
> should be pretty much complete, only initiation and running the decoder remains to be implemented

Thanks. That is fast!

I am fixing #57 so you can test it.

**Comment by jtrmal** [comment]
sorry for the delays, I will be working on it today. I should be able to make a good progress on it (no meetings).

**Comment by csukuangfj** [comment]
Thanks!

**Comment by jtrmal** [comment]
I propose we close this?

**Comment by csukuangfj** [comment]
Thanks! Addressed in https://github.com/huggingface/api-inference-community/pull/74
