### ISSUE TITLE
git clone https://www.modelscope.cn/pkufool/sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13无法下载

### ISSUE THREAD

**Issue by sqfeng-1** [k2-fsa/sherpa#512]
git下载时提示以下信息，请问有其他的链接吗，谢谢！
Cloning into 'sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13'...
fatal: https://www.modelscope.cn/pkufool/sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13/info/refs not valid: is this a git repository?

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa-ncnn/releases/tag/models
可以试试这个

**Comment by pkufool** [comment]
> git下载时提示以下信息，请问有其他的链接吗，谢谢！ Cloning into 'sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13'... fatal: https://www.modelscope.cn/pkufool/sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13/info/refs not valid: is this a git repository?

你这个地址是在哪里找的，我没传这个模型。是在哪个文档里，我修改一下。

**Comment by sqfeng-1** [comment]
谢谢！您给的新的链接，可以下载的

**Comment by sqfeng-1** [comment]
之前我是从这个链接下载的：
https://k2-fsa.github.io/sherpa/ncnn/pretrained_models/zipformer-transucer-models.html#download-the-model

**csukuangfj/sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13 (Bilingual, Chinese + English)
cd /path/to/sherpa-ncnn**

**GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/csukuangfj/sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13
cd sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13
git lfs pull --include "*.bin"**
