### ISSUE TITLE
do sherpa use espeak-ng? espeak-ng is GPL, is there any license issue?

### ISSUE THREAD

**Issue by gosailing** [k2-fsa/sherpa#529]
I found out that Sherpa tts android include such so "libespeak-ng.so", is it related to espeak-ng repo? that's a GPL, is there any license or legal risk I use sherpa tts for non-opensource since sherpa is Apache 2?

**Comment by csukuangfj** [comment]
Please have a look at the following issues/dicussions:

- https://github.com/espeak-ng/espeak-ng/issues/912
- https://github.com/rhasspy/piper/issues/93
- https://github.com/espeak-ng/espeak-ng/issues/908

Note that we are using a fork of https://github.com/rhasspy/espeak-ng that can be found at
https://github.com/csukuangfj/espeak-ng and we are using dynamic link for Android.

The owner of espeak-ng says the following:
https://github.com/espeak-ng/espeak-ng/issues/912#issuecomment-817333378

> This site of Speak NG project is used for collaboration of eSpeak NG users and developers. It is not meant neither for court nor police. If mentioned software violates license, you can report it in https://gpl-violations.org/ or https://www.gnu.org/licenses/gpl-violation.html, or similar place. Also note, that the most eager ones, who look that somebody is doing something illegal, are competitors.

**Comment by gosailing** [comment]
> Please have a look at the following issues/dicussions:
> 
> * [GPLv3 license violation espeak-ng/espeak-ng#912](https://github.com/espeak-ng/espeak-ng/issues/912)
> * [License question rhasspy/piper#93](https://github.com/rhasspy/piper/issues/93)
> * [Licensing question regarding linking espeak-ng/espeak-ng#908](https://github.com/espeak-ng/espeak-ng/issues/908)
> 
> Note that we are using a fork of https://github.com/rhasspy/espeak-ng that can be found at https://github.com/csukuangfj/espeak-ng and we are using dynamic link for Android.
> 
> The owner of espeak-ng says the following: [espeak-ng/espeak-ng#912 (comment)](https://github.com/espeak-ng/espeak-ng/issues/912#issuecomment-817333378)
> 
> > This site of Speak NG project is used for collaboration of eSpeak NG users and developers. It is not meant neither for court nor police. If mentioned software violates license, you can report it in https://gpl-violations.org/ or https://www.gnu.org/licenses/gpl-violation.html, or similar place. Also note, that the most eager ones, who look that somebody is doing something illegal, are competitors.

Thanks for quick response and you guys awesome project BTW. I got your point based on those links, we don't need involve more legal discussion. But from android area and my pass experience and https://github.com/espeak-ng/espeak-ng/issues/908, maybe the best way of using project related to espeak, such as sherpa, piper might be through IPC and opensource and deliver that part as GPL. Just for later fellow's information.
