### ISSUE TITLE
k2fsa-zipformer-chinese-english-mixed 模型需要更新

### ISSUE THREAD

**Issue by songmeixu** [k2-fsa/sherpa#545]
根据文档（https://k2-fsa.github.io/sherpa/sherpa/pretrained_models/online_transducer.html#pfluo-k2fsa-zipformer-chinese-english-mixed ）使用模型，发现模型报错（加载报错），使用 icefall 最新 export 脚本导出模型，使之被 sherpa 正常调用解码。

我在 HF 上提了 PR：https://huggingface.co/pfluo/k2fsa-zipformer-chinese-english-mixed/discussions/6  望关注。

**Comment by csukuangfj** [comment]
可以先用

https://huggingface.co/csukuangfj/k2fsa-zipformer-chinese-english-mixed
