### ISSUE TITLE
Could not find a package configuration file provided by "k2"

### ISSUE THREAD

**Issue by PeterKadima** [k2-fsa/sherpa#56]
I have successfully installed k2, but when i try to install sherpa, it came out the following errors:

```
CMake Error at cmake/k2.cmake:19 (find_package):
  By not providing "Findk2.cmake" in CMAKE_MODULE_PATH this project has asked
  CMake to find a package configuration file provided by "k2", but CMake did
  not find one.

  Could not find a package configuration file provided by "k2" with any of
  the following names:

    k2Config.cmake
    k2-config.cmake

  Add the installation prefix of "k2" to CMAKE_PREFIX_PATH or set "k2_DIR" to
  a directory containing one of the above files.  If "k2" provides a separate
  development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:44 (include)
```

**Comment by csukuangfj** [comment]
What is the output of
```
python3 -m k2.version
```
?

You have to use the latest k2.

**Comment by jtrmal** [comment]
what has worked for me is to cleanup site-packages from all k2 versions (I had a few.. not sure how that has happened) and then install the latest one. After that, all worked flawlesly

**Comment by PeterKadima** [comment]
> What is the output of
> 
> ```
> python3 -m k2.version
> ```
> 
> ?
> 
> You have to use the latest k2.
> 
> How did you install k2?

1. Here's my result of `python -m k2.version`
```
python -m k2.version
Collecting environment information...

k2 version: 1.17
Build type: Release
Git SHA1: 49b15ed91cb8b58bee5c8832bdb0a42b75520e45
Git date: Fri Jul 8 10:08:18 2022
Cuda used to build k2: 10.2
cuDNN used to build k2: 8.4.1
Python version used to build k2: 3.7
OS used to build k2:
CMake version: 3.21.3
GCC version: 8.3.1
CMAKE_CUDA_FLAGS:   -lineinfo --expt-extended-lambda -use_fast_math -Xptxas=-w  --expt-extended-lambda -gencode arch=compute_70,code=sm_70 -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options -Wall  --compiler-options -Wno-strict-overflow  --compiler-options -Wno-unknown-pragmas
CMAKE_CXX_FLAGS:  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-unused-variable  -Wno-strict-overflow
PyTorch version used to build k2: 1.10.1
PyTorch is using Cuda: 10.2
NVTX enabled: True
With CUDA: True
Disable debug: True
Sync kernels : False
Disable checks: False
Max cpu memory allocate: 214748364800
k2 abort: False
```

2. I install k2 both in the compile way and pip way.

**Comment by PeterKadima** [comment]
> th

I also tried to reinstall k2, but i still get the error.

**Comment by PeterKadima** [comment]
> what has worked for me is to cleanup site-packages from all k2 versions (I had a few.. not sure how that has happened) and then install the latest one. After that, all worked flawlesly

I also tried to reinstall k2, but i still get the error.

**Comment by csukuangfj** [comment]
> I have successfully installed k2, but when i try to install sherpa, it came out the following errors:


Can you post all the logs?

**Comment by PeterKadima** [comment]
> > I have successfully installed k2, but when i try to install sherpa, it came out the following errors:
> 
> Can you post all the logs?

@csukuangfj Here's the full log. Thanks a lot for help.
[log.txt](https://github.com/k2-fsa/sherpa/files/9076358/log.txt)

**Comment by csukuangfj** [comment]
@PeterKadima 
Thanks!

What is the output of
```bash
python3 -c "import k2; print(k2.__file__)"
```

**Comment by PeterKadima** [comment]
> @PeterKadima Thanks!
> 
> What is the output of
> 
> ```shell
> python3 -c "import k2; print(k2.__file__)"
> ```

@csukuangfj 
```
(k2) [peterKadima@DELL sherpa]$ python -c "import k2; print(k2.__file__)"

/home/peterKadima/k2/k2/python/k2/__init__.py
```

**Comment by csukuangfj** [comment]
And the output of
```
python3 -c "import torch; import _k2; print(_k2.__file__)"
```
?

Did you follow 
https://k2-fsa.github.io/k2/installation/for_developers.html
to install k2?

**Comment by PeterKadima** [comment]
> And the output of
> 
> ```
> python3 -c "import torch; import _k2; print(_k2.__file__)"
> ```
> 
> ?
> 
> Did you follow https://k2-fsa.github.io/k2/installation/for_developers.html to install k2?

Yes. But should i do that ?

**Comment by csukuangfj** [comment]
In that case, please use
```
export K2_INSTALL_PREFIX=/home/peterKadima/k2/build_release
```
before you installing `sherpa`.

(Assuming that you build directory is `build_release`).

**Comment by csukuangfj** [comment]
I am updating k2 installation doc to include that.

This is a special case and is intended for developers and advanced users only.

**Comment by csukuangfj** [comment]
I just created a PR https://github.com/k2-fsa/k2/pull/1008/files to mention that.

![Screen Shot 2022-07-09 at 20 17 59](https://user-images.githubusercontent.com/5284924/178105448-b2010840-58a8-450c-b558-754c135a0a8f.png)

**Comment by PeterKadima** [comment]
@csukuangfj Thanks for your quick response. It works perfect now. Can't wait to try sherpa. Great work!

**Comment by PeterKadima** [comment]
@csukuangfj But when i try to install k2 using conda, it came out the following error while using `python3 -m k2.version`:

```
(k2_test) [peterKadima@DELL sherpa]$ python -m k2.version
Traceback (most recent call last):
  File "/home/peterKadima/anaconda3/envs/k2_test/lib/python3.7/site-packages/k2/__init__.py", line 24, in <module>
    from _k2 import DeterminizeWeightPushingType
ImportError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/peterKadima/anaconda3/envs/k2_test/lib/python3.7/site-packages/_k2.cpython-37m-x86_64-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/peterKadima/anaconda3/envs/k2_test/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/peterKadima/anaconda3/envs/k2_test/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/peterKadima/anaconda3/envs/k2_test/lib/python3.7/site-packages/k2/__init__.py", line 31, in <module>
    str(e) + "\nNote: If you're using anaconda and importing k2 on MacOS,"
ImportError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/peterKadima/anaconda3/envs/k2_test/lib/python3.7/site-packages/_k2.cpython-37m-x86_64-linux-gnu.so)
Note: If you're using anaconda and importing k2 on MacOS,
      you can probably fix this by setting the environment variable:
  export DYLD_LIBRARY_PATH=$CONDA_PREFIX/lib/python3.7/site-packages:$DYLD_LIBRARY_PATH
(k2_test) [peterKadima@DELL sherpa]$ python -m k2.version
Traceback (most recent call last):
  File "/home/peterKadima/anaconda3/envs/k2_test/lib/python3.7/site-packages/k2/__init__.py", line 24, in <module>
    from _k2 import DeterminizeWeightPushingType
ImportError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/peterKadima/anaconda3/envs/k2_test/lib/python3.7/site-packages/_k2.cpython-37m-x86_64-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/peterKadima/anaconda3/envs/k2_test/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/peterKadima/anaconda3/envs/k2_test/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/peterKadima/anaconda3/envs/k2_test/lib/python3.7/site-packages/k2/__init__.py", line 31, in <module>
    str(e) + "\nNote: If you're using anaconda and importing k2 on MacOS,"
ImportError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/peterKadima/anaconda3/envs/k2_test/lib/python3.7/site-packages/_k2.cpython-37m-x86_64-linux-gnu.so)
Note: If you're using anaconda and importing k2 on MacOS,
      you can probably fix this by setting the environment variable:
  export DYLD_LIBRARY_PATH=$CONDA_PREFIX/lib/python3.7/site-packages:$DYLD_LIBRARY_PATH


```

**Comment by csukuangfj** [comment]
> @csukuangfj But when i try to install k2 using conda, it came out the following error while using python3 -m k2.version:

The k2 conda package is built on Ubuntu 18.04. If your system is somewhat older than Ubuntu 18.04, please consider
install k2 from source.

**Comment by PeterKadima** [comment]
> > @csukuangfj But when i try to install k2 using conda, it came out the following error while using python3 -m k2.version:
> 
> The k2 conda package is built on Ubuntu 18.04. If your system is somewhat older than Ubuntu 18.04, please consider installing k2 from source.



@csukuangfj My system is centos 7, Will this be a problem?

**Comment by csukuangfj** [comment]
Yes, that may be the problem. centos 7 was released in 2014. 

centos 8, which was released in 2019, may work.

**Comment by PeterKadima** [comment]
@csukuangfj Thanks a lot. Save a lot of time.
