### ISSUE TITLE
decoding example with no network?

### ISSUE THREAD

**Issue by jtrmal** [k2-fsa/sherpa#57]
Hi, is it possible to create an example for decoding a single wav file without need to bootstrap a server in a separate process
something like `streaming_conformer_rnnt/decode_single_file_offline.py` that would take care of setting up the decoder and feeding data into it?

**Comment by jtrmal** [comment]
If this is part of the sherpa api, then the maintanece of the huggingface plugin will be easy

**Comment by csukuangfj** [comment]
I am adding one.

**Comment by csukuangfj** [comment]
@jtrmal 

Please see https://github.com/k2-fsa/sherpa/pull/58

**Comment by jtrmal** [comment]
thanks, will look into it and get back to you today/tomorrow.
y.
