### ISSUE TITLE
Why can't I execute this compile command--------  cmake --build . --config Release –- -m:6

### ISSUE THREAD

**Issue by GrantLau1226** [k2-fsa/sherpa#594]
![Snipaste_2024-05-21_09-52-30](https://github.com/k2-fsa/sherpa/assets/87298993/1d4b799a-4cf9-4bb9-9541-7e8e2952ba53)

**Comment by csukuangfj** [comment]
Please delete
```
–- -m:6 
```
and retry.

Or you can switch to cmd and don't use powershell.

**Comment by GrantLau1226** [comment]
Thank you, I did open it using powershell and it worked after deleting -- -m:6
