### ISSUE TITLE
Is there VAD in Triton whisper?

### ISSUE THREAD

**Issue by evanxqs** [k2-fsa/sherpa#601]
There are hallucinations exist when using of Triton whisper with TensorRT-LLM in sherpa，and a VAD can solve most of hallucinations as my experience, so i wonder is there VAD in Triton whisper that i can enable it directly? or i have to integrate a new one by myself?

**Comment by yuekaizhang** [comment]
> There are hallucinations exist when using of Triton whisper with TensorRT-LLM in sherpa，and a VAD can solve most of hallucinations as my experience, so i wonder is there VAD in Triton whisper that i can enable it directly? or i have to integrate a new one by myself?

You may integrate it a new one by checking this https://github.com/k2-fsa/sherpa-onnx/blob/master/python-api-examples/vad-with-non-streaming-asr.py. Welcome to contribute if you do so.

**Comment by yuekaizhang** [comment]
Or you could do VAD at the client side.

**Comment by evanxqs** [comment]
> > There are hallucinations exist when using of Triton whisper with TensorRT-LLM in sherpa，and a VAD can solve most of hallucinations as my experience, so i wonder is there VAD in Triton whisper that i can enable it directly? or i have to integrate a new one by myself?
> 
> You may integrate it a new one by checking this https://github.com/k2-fsa/sherpa-onnx/blob/master/python-api-examples/vad-with-non-streaming-asr.py. Welcome to contribute if you do so.

silero-vad
https://github.com/snakers4/silero-vad

thank you ! and do you which vad is better?

**Comment by yuekaizhang** [comment]
> > > There are hallucinations exist when using of Triton whisper with TensorRT-LLM in sherpa，and a VAD can solve most of hallucinations as my experience, so i wonder is there VAD in Triton whisper that i can enable it directly? or i have to integrate a new one by myself?
> > 
> > 
> > You may integrate it a new one by checking this https://github.com/k2-fsa/sherpa-onnx/blob/master/python-api-examples/vad-with-non-streaming-asr.py. Welcome to contribute if you do so.
> 
> silero-vad https://github.com/snakers4/silero-vad
> 
> thank you ! and do you know which vad is better?

They are exactly same model. It's up to you.
