### ISSUE TITLE
Regarding sherpa's Benchmark for Conformer TRT encoder vs ONNX: Device Issues

### ISSUE THREAD

**Issue by NLP-yzy** [k2-fsa/sherpa#624]
I have seen Benchmark for Conformer TRT encoder vs ONNX mentioned in sherpa's official profile. can you tell me the performance of the device in question? For example, CPU cores, GPU parameters, RAM.

**Comment by csukuangfj** [comment]
@yuekaizhang could you please have a look?

**Comment by yuekaizhang** [comment]
> I have seen Benchmark for Conformer TRT encoder vs ONNX mentioned in sherpa's official profile. can you tell me the performance of the device in question? For example, CPU cores, GPU parameters, RAM.

@NLP-yzy  It's on V100 32 Gb GPU, Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz.

**Comment by shuaibique** [comment]
@yuekaizhang Thanks！

**Comment by NLP-yzy** [comment]
@yuekaizhang @csukuangfj Thanks!
