### ISSUE TITLE
PytorchStreamReader failed reading zip archive: failed finding central directory 

### ISSUE THREAD

**Issue by PPGGG** [k2-fsa/sherpa#63]
When i try to run the code below, it came out the error `PytorchStreamReader failed reading zip archive: failed finding central directory `

```
./sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_server.py \
  --port 6006 \
  --max-batch-size 50 \
  --max-wait-ms 5 \
  --nn-pool-size 1 \
  --nn-model-filename ./icefall-asr-librispeech-pruned-stateless-emformer-rnnt2-2022-06-01/exp/cpu_jit-epoch-39-avg-6-use-averaged-model-1.pt \
  --bpe-model-filename ./icefall-asr-librispeech-pruned-stateless-emformer-rnnt2-2022-06-01/data/lang_bpe_500/bpe.model
```

**Comment by csukuangfj** [comment]
1. How did you download the pre-trained model? Have you installed `git lfs`?

We have doc (https://k2-fsa.github.io/sherpa/streaming_asr/emformer/server.html#usage)
describing how to download the pre-trained model.

2. What is the output of
```
ls -lh ./icefall-asr-librispeech-pruned-stateless-emformer-rnnt2-2022-06-01/exp/
```

**Comment by PPGGG** [comment]
> 1. How did you download the pre-trained model? Have you installed `git lfs`?
> 
> We have doc (https://k2-fsa.github.io/sherpa/streaming_asr/emformer/server.html#usage) describing how to download the pre-trained model.
> 
> 2. What is the output of
> 
> ```
> ls -lh ./icefall-asr-librispeech-pruned-stateless-emformer-rnnt2-2022-06-01/exp/
> ```

Here's the output of `ls -lh ./icefall-asr-librispeech-pruned-stateless-emformer-rnnt2-2022-06-01/exp/`


```
lrwxrwxrwx 1 dell dell  46 Jul 18 13:56 cpu_jit-epoch-39-avg-6-use-averaged-model-1-torch-1.10.0.pt -> cpu_jit-epoch-39-avg-6-use-averaged-model-1.pt
-rw-rw-r-- 1 dell dell 134 Jul 18 13:56 cpu_jit-epoch-39-avg-6-use-averaged-model-1-torch-1.6.0.pt
-rw-rw-r-- 1 dell dell 134 Jul 18 13:56 cpu_jit-epoch-39-avg-6-use-averaged-model-1-torch-1.7.1.pt
-rw-rw-r-- 1 dell dell 134 Jul 18 13:56 cpu_jit-epoch-39-avg-6-use-averaged-model-1.pt
-rwxrwxr-x 1 dell dell 592 Jul 18 13:56 decode-pruned-stateless-emformer-rnnt-full-2-2.sh
-rwxrwxr-x 1 dell dell 767 Jul 18 13:56 export.sh
drwxrwxr-x 2 dell dell 318 Jul 18 13:56 log
-rw-rw-r-- 1 dell dell 134 Jul 18 13:56 pretrained-epoch-39-avg-6-use-averaged-model-1.pt
-rwxrwxr-x 1 dell dell 469 Jul 18 13:56 run-pruned-stateless-emformer-rnnt-full-2.sh
drwxrwxr-x 2 dell dell 102 Jul 18 13:56 tensorboard
```

**Comment by csukuangfj** [comment]
> -rw-rw-r-- 1 dell dell 134 Jul 18 13:56 cpu_jit-epoch-39-avg-6-use-averaged-model-1.pt

It shows that you did not download the pre-trained model successfully. The `.pt` file is less than 200 bytes!

Please do 
```
cd icefall-asr-librispeech-pruned-stateless-emformer-rnnt2-2022-06-01
git lfs pull
ls -lh exp
```
and please post the above output.

**Comment by PPGGG** [comment]
> > -rw-rw-r-- 1 dell dell 134 Jul 18 13:56 cpu_jit-epoch-39-avg-6-use-averaged-model-1.pt
> 
> It shows that you did not download the pre-trained model successfully. The `.pt` file is less than 200 bytes!
> 
> Please do
> 
> ```
> cd icefall-asr-librispeech-pruned-stateless-emformer-rnnt2-2022-06-01
> git lfs pull
> ls -lh exp
> ```
> 
> and please post the above output.

Thanks a lot. Everything works now ！
