### ISSUE TITLE
Streaming ASR model support question

### ISSUE THREAD

**Issue by PPGGG** [k2-fsa/sherpa#64]
I noticed that now sherpa support `pruned_stateless_emformer_rnnt2 ` for streaming ASR.

I would like to know whether sherpa support streaming ASR with another model, such as `pruned_transducer_stateless x` (x means 1, 2, 3, 4 and so on) or `conv_emformer_transducer_stateless x` ?

Thanks a lot.

**Comment by csukuangfj** [comment]
> I would like to know whether sherpa support streaming ASR with another model, such as pruned_transducer_stateless x

Please see https://github.com/k2-fsa/sherpa/tree/master/sherpa/bin
