### ISSUE TITLE
How to support language auto-detection instead of given a specific language

### ISSUE THREAD

**Issue by evanxqs** [k2-fsa/sherpa#640]
It has to specify the language when use triton client to invoke triton server with prompts as below:
"<|startoftranscript|><|en|><|transcribe|><|notimestamps|>",
But how to set language auto-detection if not sure which language the audio contains?
I try to remove <|en|> but exception would raise. There're two issues:
1. how to set language auto-detection?
2. prompts will overflow if i add more languages as below:
["zh", "en", "zh_en", "jp", "ko", "fr", "de", "es", "it", "pt", "ru", "ar", "tr", "vi", "th", "id", "ms", "hi", "bn", "ta", "te", "ml", "mr", "ur", "fa", "ps", "sd", "ne", "pa", "gu", "or", "as", "kn", "ml", "si", "my"]
What are the maximum chars of prompts? How to avoid prompts overflow issue?

![image](https://github.com/user-attachments/assets/f22335ff-176c-4372-8827-a749955d4dd0)
![image](https://github.com/user-attachments/assets/47e902d9-2c9f-43c9-bc09-6f59656647e3)
![image](https://github.com/user-attachments/assets/9411a63b-5849-4c33-b46c-7ffcfa6b8226)

**Comment by csukuangfj** [comment]
@yuekaizhang  Could you give it a look?

**Comment by yuekaizhang** [comment]
@evanxqs 

Hi,

1. We currently didn't implement it. For lang_id, you could use tensorrt engine to do one encoder forward run and one decoder forward run. The encoder forward run could be reused by later decoding process. Also, you could use external lang_id model, which should be faster comparing with whisper decoder 1B run.

2. You could increase it `--max_input_len 14 \` when building decoder trt-llm engine. However, I think it should be better for accuracy if you only use one or two lang_id as the prompt here.
