### ISSUE TITLE
Help in compiling Sherpa as a standalone static executable

### ISSUE THREAD

**Issue by danielizham** [k2-fsa/sherpa#645]
Is there a way to make the generated binaries (i.e. sherpa-online, sherpa-online-websocket-client, sherpa-online-websocket-server, etc.) standalone and not use the dynamic loader?

I'm afraid my understanding of CMake is very basic so I don't understand much of the CMakeLists.txt files in Sherpa. Based on my search, I tried adding the `static` flag to all the `target_link_libraries` but the build failed and I couldn't debug it due to my limited knowledge. Is this the right approach or is there an easier way to link the required libraries statically?

**Comment by csukuangfj** [comment]
could you try sherpa-onnx?

**Comment by csukuangfj** [comment]
If you indeed want to use pytorch libs, please have a look at
https://github.com/csukuangfj/torch-libs/tree/linux/cmake

we provide pre-built static libraries for PyTorch. You can follow what we are doing in k2-fsa/sherpa-onnx for building binaries with static link.

**Comment by danielizham** [comment]
I haven't tried sherpa-onnx yet. We'll give it a try once we figure out how to export our model to the onnx format.

As for using this version of Sherpa, would following where the `static` keyword is being used in the CMakeLists.txt files in sherpa-onnx and applying the same to CMakeLists.txt files for this pytorch Sherpa be enough to create the standalone binaries (in addition to pointing to the pre-built static libraries for PyTorch)?

**Comment by csukuangfj** [comment]
> If you indeed want to use pytorch libs, please have a look at https://github.com/csukuangfj/torch-libs/tree/linux/cmake
> 
> we provide pre-built static libraries for PyTorch. You can follow what we are doing in k2-fsa/sherpa-onnx for building binaries with static link.

If you follow this comment, you will be able to achieve what you want.

**Comment by csukuangfj** [comment]
I recommend again that you should try sherpa-onnx if you want to use a static build.

**Comment by danielizham** [comment]
Thank you!
