### ISSUE TITLE
Add new beam search methods

### ISSUE THREAD

**Issue by ezerhouni** [k2-fsa/sherpa#67]
This issue is about adding new beam search methods, similarly found in ```icefall```. Examples are (but not limited) : 

- ```fast_beam_search_nbest_LG```
- ```fast_beam_search_nbest```
- ```fast_beam_search_with_nbest_rescoring```

Todo : 

- [x] https://github.com/k2-fsa/sherpa/issues/67#issuecomment-1190412338
- [x] https://github.com/k2-fsa/sherpa/pull/68#discussion_r926201473

This issue is also useful to centralize all questions that can arise while doing the implementation.

cc @csukuangfj @pkufool

**Comment by csukuangfj** [comment]
Thanks for your contribution.

**Comment by csukuangfj** [comment]
> Could you check if you have another model that I could test ? Otherwise I can create a "fake" one and use it to test the code.

Where did you get the following model?
```
  --bpe-model-filename models/icefall-asr-librispeech-conv-emformer-transducer-stateless-2022-06-11/data/lang_bpe_500/bpe.model
```

Please use
https://github.com/k2-fsa/sherpa/blob/fb0ee4adfdd5e490111ada244e0713410561d2dd/.github/workflows/run-streaming-conv-emformer-test.yaml#L112

---

@yaozengwei 

Please add documentation for https://github.com/k2-fsa/sherpa/pull/49
In a sense, documentation is as important as the code. Please don't forget adding documentation describing
how to use your code.

**Comment by csukuangfj** [comment]
@ezerhouni 

Sorry for the inconsistent naming convention between sherpa and icefall.

Would you mind updating the directory name in `sherpa/bin` to match that from icefall?

For instance, 
- `sherpa/bin/conv_emformer_transducer_stateless` should be named as `sherpa/bin/conv_emformer_transducer_stateless2`
- `sherpa/bin/conformer_rnnt` should be named as `sherpa/bin/pruned_transducer_statelessX`. We use `X` since it 
corresponds to `pruned_transducer_stateless2`, `pruned_transducer_stateless3`, etc, in icefall
- `sherpa/bin/streaming_conformer_rnnt` should be names as `sherpa/bin/streaming_pruned_transducer_statelessX`. It is a streaming version of `pruned_transducer_statelessX`.

**Comment by ezerhouni** [comment]
@csukuangfj No worries !
Sure thing, I will first finish what I am working on (conv_emformer). Then I will do the renaming + the pre-commit to have more consistency

**Comment by csukuangfj** [comment]
> Secondly, if I am not mistaken, there is not pre-commit hook à la ```icefall``` should we add one (the same as icefall should do the work as a first step)

Yes. Would be nice if you can add that.

**Comment by yaozengwei** [comment]
> > Could you check if you have another model that I could test ? Otherwise I can create a "fake" one and use it to test the code.
> 
> Where did you get the following model?
> 
> ```
>   --bpe-model-filename models/icefall-asr-librispeech-conv-emformer-transducer-stateless-2022-06-11/data/lang_bpe_500/bpe.model
> ```
> 
> Please use
> 
> https://github.com/k2-fsa/sherpa/blob/fb0ee4adfdd5e490111ada244e0713410561d2dd/.github/workflows/run-streaming-conv-emformer-test.yaml#L112
> 
> @yaozengwei
> 
> Please add documentation for #49 In a sense, documentation is as important as the code. Please don't forget adding documentation describing how to use your code.

@ezerhouni Sorry for confusion. I will add the doc.

**Comment by ezerhouni** [comment]
@yaozengwei No worries !
I will add the refactoring into the todo @csukuangfj

**Comment by yaozengwei** [comment]
[https://github.com/k2-fsa/sherpa/pull/69](url) adds documents for ConvEmformer.

**Comment by ezerhouni** [comment]
@csukuangfj I am closing this issue. Once I am back I will work on other beam search function

**Comment by csukuangfj** [comment]
Thanks!

**Comment by pingfengluo** [comment]
@csukuangfj @pkufool Are there any plans to support a  C++ version for fast_beam_search ?

**Comment by pkufool** [comment]
> @csukuangfj @pkufool Are there any plans to support a C++ version for fast_beam_search_nbest_LG ?

I think all the key algorithms needed by `fast_beam_search_nbest_LG` are implemented in k2 with C++, so we don't have plan to add c++ version to sherpa right now, except that current implementation would get severe efficiency degradation.

**Comment by danpovey** [comment]
> > @csukuangfj @pkufool Are there any plans to support a C++ version for fast_beam_search_nbest_LG ?
> 
> I think all the key algorithms needed by `fast_beam_search_nbest_LG` are implemented in k2 with C++, so we don't have plan to add c++ version to sherpa right now, except that current implementation would get severe efficiency degradation.

Could you please expand on this?  degradation relative to what, and why?

**Comment by pkufool** [comment]
> > > @csukuangfj @pkufool Are there any plans to support a C++ version for fast_beam_search_nbest_LG ?
> > 
> > 
> > I think all the key algorithms needed by `fast_beam_search_nbest_LG` are implemented in k2 with C++, so we don't have plan to add c++ version to sherpa right now, except that current implementation would get severe efficiency degradation.
> 
> Could you please expand on this? degradation relative to what, and why?

No, I have nothing to say, I just told him we won't consider to add C++ implementation to sherpa before we find efficiency problem with python.

**Comment by danpovey** [comment]
Oh, OK, cool.  I would have said "... unless the current implementation would give a severe efficiency degradation".
