### ISSUE TITLE
KeywordSpotter 能否单独暴露到 C API 中

### ISSUE THREAD

**Issue by endink** [k2-fsa/sherpa#673]
现在 KeywordSpotter 没有导出，如果编译动态库只能修改源码

**Comment by csukuangfj** [comment]
可否使用 sherpa-onnx?

**Comment by endink** [comment]
就是用 sherpa-onnx， 例如想实现得到唤醒词后提示一个语音，这种自定义逻辑，asr 和 KeywordSpotter  合在一起就很难搞

**Comment by endink** [comment]
还有，例如 KeywordSpotter  在本地， TTS 是服务器，也很难搞，如果能独立 export 出来更加灵活

**Comment by csukuangfj** [comment]
sherpa-onnx 里面，是不是 c api 里面，已经有了 keyword spotter?

keyword spotter 是不是已经和 asr 是分开的？

**Comment by endink** [comment]
没有， SherpaOnnxKeywordSpotter 只有一个结构定义，函数都没导出， 现在是靠自己改代码

**Comment by endink** [comment]
哦，我知道了，你的意思是用 C API， 我在用 C++

**Comment by endink** [comment]
C API 确实有，不好意思

**Comment by endink** [comment]
另外 text2token.py 这个 C/C++ 实现有代码可以参考吗？ 文档只说用 python
