### ISSUE TITLE
deletion using fast_beam_search and greedy_search

### ISSUE THREAD

**Issue by ngoel17** [k2-fsa/sherpa#74]
I am getting  too many deletions as follows:
   If I decode using ./pruned_transducer_stateless2/decode.py  --iter 328000  --avg 28  --simulate-streaming 1   --causal-convolution 1  --decode-chunk-size 16  --left-context 64  --exp-dir ./pruned_transducer_stateless2/exp_old  --max-duration 600   --beam 2.0  --max-contexts 8  --decoding-method fast_beam_search  --max-states 32 

 then the WER is pretty decent (9.xx% range)
   But if I do --- 
   pruned_transducer_stateless2/export.py --jit 1 --iter 328000   --avg 28  --exp-dir ./pruned_transducer_stateless2/exp_old

  and then do client server in sherpa using - 

   ./sherpa/bin/streaming_conformer_rnnt/streaming_server.py  --port 6007  --max-batch-size 500  --max-wait-ms 50  --max-active-connections 500  --nn-model-filename pruned_transducer_stateless2/exp_old/cpu_jit.pt --bpe-model-filename data/lang_bpe_500/bpe.model  --decoding-method fast_beam_search  --beam 2

  Then the deletion rate is very high.

  I am trying to have the exact same test data and the same search parameters in the two examples above.

**Comment by csukuangfj** [comment]
@pkufool  Could you please have a look at it?

**Comment by ngoel17** [comment]
adding    --streaming-model 1 --causal-convolution 1   parameters to the export.py solved the issue.
