### ISSUE TITLE
RTF for cpu

### ISSUE THREAD

**Issue by lalimili6** [k2-fsa/sherpa#75]
Hi dear,
can report RTF for cpu? 
best regards

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa#rtf-test

<img width="938" alt="Screen Shot 2022-07-22 at 2 06 08 PM" src="https://user-images.githubusercontent.com/5284924/180374105-65717a7d-cd5b-435e-a732-ab007a0596a5.png">


Can you use the above [colab notebook](https://colab.research.google.com/drive/1JX5Ph2onYm1ZjNP_94eGqZ-DIRMLlIca?usp=sharing) to measure RTF for CPU.
(The default is using GPU).

A PR is welcome if you can do that. 

Thanks

**Comment by ezerhouni** [comment]
@csukuangfj Actually I was about to create an issue to tackle it (to also have an RTF for streaming model, etc) :)

**Comment by csukuangfj** [comment]
> @csukuangfj Actually I was about to create an issue to tackle it (to also have an RTF for streaming model, etc) :)

That would be very nice of you. If @lalimili6 does not respond, I suggest that you can just start it.

**Comment by ezerhouni** [comment]
> > @csukuangfj Actually I was about to create an issue to tackle it (to also have an RTF for streaming model, etc) :)
> 
> That would be very nice of you. If @lalimili6 does not respond, I suggest that you can just start it.

I will work first on the refactoring of the beam search, if time allows I will give a look to RTF

**Comment by ezerhouni** [comment]
@csukuangfj Also, I was thinking to maybe add the RTF in Results.md in ```icefall```, to give a sense of how much CPU/GPU usage it needs (so not only comparing WER but also RTF), wdyt ?

**Comment by csukuangfj** [comment]
> @csukuangfj Also, I was thinking to maybe add the RTF in Results.md in `icefall`, to give a sense of how much CPU/GPU usage it needs (so not only comparing WER but also RTF), wdyt ?

Yes, that is a good idea. I also suggest adding the number of parameters of the model to RESULTS.md.

Since RTF depends on what hardware you are using, shall we also list the environment in which RTF is measured?

**Comment by ezerhouni** [comment]
> I also suggest adding the number of parameters of the model to RESULTS.md.

Agree !

> Since RTF depends on what hardware you are using, shall we also list the environment in which RTF is measured?

Yes, testing for both CPU and GPU, with description of hardware + software (cuda, cudnn, etc).

**Comment by ezerhouni** [comment]
@csukuangfj I tried to add the RTF for the streaming pipeline. However, I keep having ```sent 1011 (unexpected error) keepalive ping timeout; no close frame received``` any idea why ? (I can create a PR for you to have a look into the code if you want)

**Comment by csukuangfj** [comment]
> @csukuangfj I tried to add the RTF for the streaming pipeline. However, I keep having `sent 1011 (unexpected error) keepalive ping timeout; no close frame received` any idea why ? (I can create a PR for you to have a look into the code if you want)

Thanks for testing it.

I think it is the same error reported in https://github.com/k2-fsa/sherpa/issues/84

I will look into it during the weekend.

**Comment by lalimili6** [comment]
Here are results
https://github.com/k2-fsa/sherpa/pull/168
many thanks
