### ISSUE TITLE
C++ interface

### ISSUE THREAD

**Issue by pingfengluo** [k2-fsa/sherpa#85]
@csukuangfj @pkufool  will Sherpa support full C++ interface and runtime?
In speech recognition application scenarios such as voice input method (running on IOS, Android, IOT), smart home appliances (or other IOT devices), and audio content understanding...the device and system where the algorithm runs may not have the Python runtime, and a more general approach may be Is to support the full C++ interface and runtime, and the main reasons are
1. For example, the IOT device has very little memory and cannot install Python packages
2. Operating systems like IOS, Android, and EmbedLinux have one thing in common is that they can run C++ runtime
3. Many codes of Cloud services and existing business systems are written based on C++/Java(Java can call C++ runtime by JNI)

Some existing interfaces :  https://github.com/alphacep/vosk-api/blob/master/src/vosk_api.h  and https://github.com/skit-ai/kaldi-serve/tree/master/include/kaldiserve . The vosk_api.h supports Kaldi, and now Wenet also has corresponding implementations.

**Comment by csukuangfj** [comment]
Thanks for the issue.

Yes, I think we should provide a C/C++ runtime without depending on Python so that we can deploy sherpa on embedded devices, such as mobile phones. An all-in-one C/C++ library also makes it easier to integrate with existing services/systems that are using C++.

We can still support a Python frontend in sherpa. The two don't conflict with each other.

@danpovey @pkufool 
What do you think?

**Comment by danpovey** [comment]
I agree, this is something we should aim for.  However, I don't think we need to be too aggressive about its timeline right now.  We still have work to do on the core stuff like improving the WER, getting fast inference, and so on; and once we demonstrate good performance in that respect, we can easily get more resources at Xiaomi to help us with the more mechanical aspects of the project like the C++ inference.

**Comment by minmin0** [comment]
Is there any new progress?
