### ISSUE TITLE
ImportError: cannot import name 'RnntEmformerModel' from 'sherpa'

### ISSUE THREAD

**Issue by shushanxingzhe** [k2-fsa/sherpa#9]
I installed sherpa on Windows. When I run the demo, I got the error "ImportError: cannot import name 'RnntEmformerModel' from 'sherpa'". Please help

**Comment by csukuangfj** [comment]
Sorry, it is not tested on windows.

Please use macOS or Linux.

Will try to support windows.

**Comment by shushanxingzhe** [comment]
Very thanks for your reply. I have solved this problem by uninstall and installing from source code again

**Comment by csukuangfj** [comment]
Glad to hear that.

**Comment by csukuangfj** [comment]
It should support Windows now. Closing.
